# SPDX-FileCopyrightText: Copyright (c) 2025-2026, NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

{{- if .Values.service }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "vss-summarization.serviceName" . }}
  labels:
    {{- include "vss-summarization.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    {{- if .Values.service.ports }}
    {{- range .Values.service.ports }}
    {{- $port := .port }}
    - port: {{ .port }}
      {{- with .targetPort }}
      {{- if ne (toString .) (toString $port) }}
      targetPort: {{ . }}
      {{- end }}
      {{- end }}
      protocol: {{ .protocol | default "TCP" }}
      {{- if .name }}
      name: {{ .name }}
      {{- end }}
      {{- if .nodePort }}
      nodePort: {{ .nodePort }}
      {{- end }}
    {{- end }}
    {{- else }}
    - port: {{ .Values.service.port }}
      targetPort: app-port
      protocol: TCP
      name: app-port
      {{- if .Values.service.nodePort }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
    {{- end }}
  selector:
    {{- include "vss-summarization.selectorLabels" . | nindent 4 }}
{{- if (and .Values.statefulSet (.Values.statefulSet.enabled | default false)) }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "vss-summarization.headlessServiceName" . }}
  labels:
    {{- include "vss-summarization.labels" . | nindent 4 }}
spec:
  clusterIP: None
  publishNotReadyAddresses: true
  ports:
    {{- if .Values.service.ports }}
    {{- range .Values.service.ports }}
    {{- $port := .port }}
    - port: {{ .port }}
      {{- with .targetPort }}
      {{- if ne (toString .) (toString $port) }}
      targetPort: {{ . }}
      {{- end }}
      {{- end }}
      protocol: {{ .protocol | default "TCP" }}
      {{- if .name }}
      name: {{ .name }}
      {{- end }}
    {{- end }}
    {{- else }}
    - port: {{ .Values.service.port }}
      targetPort: app-port
      protocol: TCP
      name: app-port
    {{- end }}
  selector:
    {{- include "vss-summarization.selectorLabels" . | nindent 4 }}
{{- end }}
{{- end }}
