# SPDX-FileCopyrightText: Copyright (c) 2025-2026, NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

{{- if (and .Values.statefulSet (.Values.statefulSet.enabled | default false)) }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "vss-summarization.fullname" . }}
  labels:
    {{- include "vss-summarization.labels" . | nindent 4 }}
spec:
  {{- if not (and .Values.autoscaling .Values.autoscaling.enabled) }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "vss-summarization.selectorLabels" . | nindent 6 }}
  serviceName: {{ include "vss-summarization.headlessServiceName" . }}
  podManagementPolicy: "Parallel"
  template:
    {{- include "vss-summarization.podTemplateSpec" . | nindent 4 }}
  {{- with .Values.statefulSet.persistentVolumeClaimRetentionPolicy }}
  persistentVolumeClaimRetentionPolicy:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.statefulSet.volumeClaimTemplates }}
  volumeClaimTemplates:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
