# SPDX-FileCopyrightText: Copyright (c) 2025-2026, NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: "mgdino_postprocess"
backend: "python"
max_batch_size: 32
input [
{
    name: "pred_logits"
    data_type: TYPE_FP32
    dims: [ 900, 256]
},
{
    name: "pred_boxes"
    data_type: TYPE_FP32
    dims: [ 900, 4]
}
,
{
    name: "pos_map"
    data_type: TYPE_FP32
    dims: [ -1,256]
}
,
{
    name: "target_sizes"
    data_type: TYPE_INT32
    dims: [4]
},
{
    name: "pred_masks"
    data_type: TYPE_FP32
    dims: [ 900, 1, 136, 240]
}
]

output [
{
    name: "labels"
    data_type: TYPE_INT32
    dims: [ -1,300]
},
{
    name: "boxes"
    data_type: TYPE_FP32
    dims: [ -1,300, 4]
}
,
{
    name: "scores"
    data_type: TYPE_FP32
    dims: [ -1,300]
},
{
    name: "masks"
    data_type: TYPE_FP32
    dims: [ -1,300, 1, 136, 240]
}
]

instance_group [{ kind: KIND_GPU }]


#dynamic_batching {
    # max_queue_delay_microseconds: 20000
#}
