#!/usr/bin/env python3
# SPDX-FileCopyrightText: Copyright (c) 2026, NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
"""Generate a deterministic third-party notice from an installed Python env.

Run this script with the interpreter from a runtime-only, frozen environment.
For example::

    UV_PROJECT_ENVIRONMENT=.license-venv uv sync --python 3.13 --frozen --no-default-groups
    .license-venv/bin/python ../../.github/scripts/generate_python_license_notice.py \
        --output LICENSE-3rd-party.txt --exclude nvidia-vss-cli

The generator fails closed when a distribution has no installed license or
notice file.  That prevents a dependency update from silently producing an
incomplete attribution bundle.
"""

from __future__ import annotations

import argparse
import importlib.metadata
import re
import sys
from pathlib import Path, PurePosixPath


NOTICE_BASENAMES = ("license", "copying", "notice", "copyright")


def canonical_name(value: str) -> str:
    """Return the PEP 503 normalized distribution name."""

    return re.sub(r"[-_.]+", "-", value).lower()


def _is_notice_file(path: PurePosixPath) -> bool:
    name = path.name.lower()
    return any(name.startswith(prefix) for prefix in NOTICE_BASENAMES)


def _project_url(metadata: importlib.metadata.PackageMetadata) -> str:
    for entry in metadata.get_all("Project-URL") or ():
        label, separator, url = entry.partition(",")
        if separator and label.strip().lower() in {
            "homepage",
            "home",
            "repository",
            "source",
        }:
            return url.strip()
    return metadata.get("Home-page", "").strip()


def _license_name(metadata: importlib.metadata.PackageMetadata) -> str:
    return (
        metadata.get("License-Expression", "").strip()
        or metadata.get("License", "").strip()
        or "See installed license files"
    )


def render_notice(excluded: set[str]) -> str:
    distributions = sorted(
        (
            distribution
            for distribution in importlib.metadata.distributions()
            if canonical_name(distribution.metadata.get("Name", "")) not in excluded
        ),
        key=lambda distribution: canonical_name(distribution.metadata.get("Name", "")),
    )

    missing: list[str] = []
    entries: list[str] = []
    for distribution in distributions:
        name = distribution.metadata.get("Name", "").strip()
        if not name:
            continue

        notice_paths = sorted(
            (
                file
                for file in distribution.files or ()
                if any(
                    part.endswith(".dist-info")
                    for part in PurePosixPath(str(file)).parts
                )
                and _is_notice_file(PurePosixPath(str(file)))
            ),
            key=lambda file: str(file).lower(),
        )
        if not notice_paths:
            missing.append(f"{name}=={distribution.version}")
            continue

        project_url = _project_url(distribution.metadata)
        lines = [
            "--------------------------------------------------------------------------------",
            "",
            f"## {name} ({distribution.version})",
            "",
            f"**License:** {_license_name(distribution.metadata)}",
        ]
        if project_url:
            lines.extend(("", f"**Project URL:** {project_url}"))

        for notice_path in notice_paths:
            installed_path = distribution.locate_file(notice_path)
            try:
                content = installed_path.read_text(encoding="utf-8").rstrip()
            except UnicodeDecodeError:
                content = installed_path.read_text(encoding="latin-1").rstrip()
            content = re.sub(r"[ \t]+$", "", content, flags=re.MULTILINE)
            lines.extend(
                (
                    "",
                    f"**Installed notice:** `{notice_path}`",
                    "",
                    "````text",
                    content,
                    "````",
                )
            )
        entries.append("\n".join(lines))

    if missing:
        raise RuntimeError(
            "installed distributions without a license/notice file: "
            + ", ".join(missing)
        )

    header = [
        "# Dependencies Licenses",
        "",
        "This file contains the installed license and notice texts for the frozen,",
        "default runtime dependencies of `nvidia-vss-cli`.",
        "",
        "It is generated by `.github/scripts/generate_python_license_notice.py`;",
        "do not copy the agent notice or edit this file by hand.",
        "",
        f"Total packages: {len(entries)}",
        "",
        "---",
        "",
    ]
    return "\n".join(header + entries) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output", type=Path, required=True)
    parser.add_argument("--exclude", action="append", default=[])
    parser.add_argument(
        "--check",
        action="store_true",
        help="fail if the generated text differs instead of updating the output",
    )
    args = parser.parse_args()

    excluded = {canonical_name(name) for name in args.exclude}
    generated = render_notice(excluded)
    if args.check:
        existing = (
            args.output.read_text(encoding="utf-8") if args.output.exists() else ""
        )
        if existing != generated:
            print(
                f"ERROR: {args.output} is stale; regenerate it from the frozen runtime environment.",
                file=sys.stderr,
            )
            return 1
        return 0

    args.output.write_text(generated, encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
