# SPDX-FileCopyrightText: Copyright (c) 2025-2026, NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

{{- if and .Values.enabled (or (eq .Values.profileMode "alerts") (eq .Values.profileMode "search")) }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "vss-rtvi-cv.fullname" . }}-ds-start
  labels:
    {{- include "vss-rtvi-cv.labels" . | nindent 4 }}
data:
  ds-start.sh: |
{{ .Files.Get "files/ds-start.sh" | indent 4 }}
  download-models.sh: |
{{ .Files.Get "files/download-models.sh" | indent 4 }}
  {{- if .Values.downloadModelsFromNgc }}
  models-download.json: |
    {
      "downloads": [
{{- range $i, $m := .Values.ngcModelsToDownload }}
        {
          "model": {{ $m.model | quote }},
          "sourcePath": {{ $m.sourcePath | quote }},
          "destPath": {{ $m.destPath | quote }},
          "org": {{ $m.org | default $.Values.ngcOrg | quote }}
        }{{ if lt (add $i 1) (len $.Values.ngcModelsToDownload) }},{{ end }}
{{- end }}
      ]
    }
  {{- end }}
{{- end }}
