# SPDX-FileCopyrightText: Copyright (c) 2025-2026, NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: v2
name: vss
description: "VSS stack - Helm chart for developer profiles - LVS (Long Video Summarization)"
type: application
version: 26.04.1
appVersion: "26.04.1"
dependencies:
  - name: phoenix
    version: "0.1.0"
    repository: "file://./charts/phoenix"
    condition: phoenix.enabled
  - name: redis
    version: "0.1.0"
    repository: "file://./charts/redis"
    condition: redis.enabled
  - name: centralizedb-dev
    version: "0.1.0"
    repository: "file://./charts/centralizedb-dev"
    condition: centralizedb-dev.enabled
  - name: envoy-streamprocessing
    version: "0.1.0"
    repository: "file://./charts/envoy-streamprocessing"
    condition: envoy-streamprocessing.enabled
  - name: sdr-streamprocessing
    version: "0.1.0"
    repository: "file://./charts/sdr-streamprocessing"
    condition: sdr-streamprocessing.enabled
  - name: sensor-ms-dev
    version: "0.1.0"
    repository: "file://./charts/sensor-ms-dev"
    condition: sensor-ms-dev.enabled
  - name: streamprocessing-ms-dev
    version: "0.1.0"
    repository: "file://./charts/streamprocessing-ms-dev"
    condition: streamprocessing-ms-dev.enabled
  - name: vst-ingress-dev
    version: "0.1.0"
    repository: "file://./charts/vst-ingress-dev"
    condition: vst-ingress-dev.enabled
  - name: vst-mcp-dev
    version: "0.1.0"
    repository: "file://./charts/vst-mcp-dev"
    condition: vst-mcp-dev.enabled
  - name: vss-agent
    version: "0.1.0"
    repository: "file://./charts/vss-agent"
    condition: vss-agent.enabled
  - name: vss-ui
    version: "0.1.0"
    repository: "file://./charts/vss-ui"
    condition: vss-ui.enabled
  - name: nims
    version: "0.1.0"
    repository: "file://./charts/nims"
    condition: nims.enabled
  - name: rtvi-vlm
    version: "0.1.0"
    repository: "file://./charts/rtvi-vlm"
    condition: rtvi-vlm.enabled
  - name: lvs-server
    version: "0.1.0"
    repository: "file://./charts/lvs-server"
    condition: lvs-server.enabled
  - name: elasticsearch
    version: "0.1.0"
    repository: "file://./charts/elasticsearch"
    condition: elasticsearch.enabled
  - name: kibana
    version: "0.1.0"
    repository: "file://./charts/kibana"
    condition: kibana.enabled
  - name: elasticsearch-init-container
    version: "0.1.0"
    repository: "file://./charts/elasticsearch-init-container"
    condition: elasticsearch-init-container.enabled
  - name: kibana-init-container-lvs
    version: "0.1.0"
    repository: "file://./charts/kibana-init-container-lvs"
    condition: kibana-init-container-lvs.enabled
  - name: vss-proxy
    version: "0.1.0"
    repository: "file://./charts/vss-proxy"
    condition: vss-proxy.enabled
maintainers: []
