commons:
  prerequisites:
    auto-calibration:
      - operation_type: "file_management"
        enabled: false
        target_directories:
          - "${VSS_DATA_DIR}/videos/${SAMPLE_VIDEO_DATASET}"
        file_management:
          action: "keep_count" # Keep only the last ${final_stream_count} videos in the directory
          parameters:
            count: ${final_stream_count}
            pattern: "*.mp4"

  variables:
    auto-calibration:
      - final_stream_count: "${NUM_STREAMS}"

  file_operations:
    auto-calibration:
    variables:
      - operation_type: "json_update"
        target_file: "${VSS_APPS_DIR}/services/nvstreamer/configs/vst-config.json"
        backup: true 
        updates:
          data.nv_streamer_sync_file_count: ${final_stream_count}

      # Update the VST Configs
      - operation_type: "json_update"
        target_file: "${VSS_APPS_DIR}/industry-profiles/warehouse-operations/warehouse-2d-app/vst/configs/vst_config.json"
        backup: true
        updates:
          onvif.max_devices_supported: ${effective_max_streams_supported}
          data.always_recording: true

      - operation_type: "file_management"
        enabled: false
        target_directories:
          - "${VSS_DATA_DIR}/videos/${SAMPLE_VIDEO_DATASET}"
        file_management:
          action: "keep_count" # Keep only the last ${final_stream_count} videos in the directory
          parameters:
            count: ${final_stream_count}
            pattern: "*.mp4"