#!/usr/bin/env python3

# SPDX-FileCopyrightText: Copyright (c) 2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
#
# SPDX-License-Identifier: Apache-2.0


import carla
import numpy as np
import cv2
import argparse
import math
import time
from typing import List, Tuple, Dict, Any
import urllib.parse
import requests
import yaml
import os
from pathlib import Path
import xml.etree.ElementTree as ET
from pyproj import CRS, Transformer
import logging
from PIL import Image
import rasterio
import re
from rasterio.transform import from_origin

logging.basicConfig(
    level=logging.INFO,
    format="[%(asctime)s] {%(filename)s:%(lineno)d} {%(processName)s:%(process)d} - %(levelname)s - %(message)s",  # noqa: E501
    datefmt="%H:%M:%S",
)
logger = logging.getLogger(__name__)
PGM_PATH = os.getenv("PGM_PATH", "/opt/geoids/egm96-15.pgm")


def generate_satellite_image_url(
    center_lat: float,
    center_lon: float,
    path_coordinates: List[Tuple[float, float]],
    api_key: str,
    size: str = "1920x1080",
    maptype: str = "satellite",
    path_color: str = "0xFF0000FF",
    path_weight: int = 5,
    zoom: int = 21,
):
    """
    Create a satellite image using google map API url
    Args:
        center_lat (float): Latitude of the map center.
        center_lon (float): Longitude of the map center.
        path_coordinates (List[Tuple[float, float]]): List of (lat, lon) tuples
                                                      defining the road segment polyline.
        api_key (str): Your Google Maps API Key.
        size (str): Image size in pixels (e.g., '1920x1080').
        maptype (str): Type of map (e.g., 'satellite', 'roadmap').
        path_color (str): Hex color code for the path (e.g., '0xFF0000FF' for solid red).
        path_weight (int): Thickness of the path line in pixels.
        zoom (int): Zoom level (e.g., 18 for street view, 8 for city view).
    Returns:
        str: The fully constructed and encoded Google Maps Static API URL.
    """
    BASE_URL = "https://maps.googleapis.com/maps/api/staticmap?"

    params = {
        "center": f"{center_lat},{center_lon}",
        "zoom": zoom,
        "size": size,
        "maptype": maptype,
        "key": api_key,
    }
    if path_coordinates:
        first_coordinate = path_coordinates[0]
        path_coordinates.append(first_coordinate)
    coord_strings = [f"{lat},{lon}" for lat, lon in path_coordinates]
    path_coords_str = "|".join(coord_strings)
    path_str = f"color:{path_color}|weight:{path_weight}|{path_coords_str}"
    params["path"] = path_str
    query_string = urllib.parse.urlencode(params)
    final_url = BASE_URL + query_string

    return final_url


def download_and_save_image(
    url: str, filename: str = "google_map_trace.png", save_dir: str = "/tmp/"
):
    """
    Downloads the image from the constructed URL and saves it to the specified directory.

    Args:
        url (str): The Google Maps Static API URL generated by the function.
        filename (str): The name for the saved file.
        save_dir (str): The directory where the file will be saved (defaults to /tmp/).
    """

    full_path = os.path.join(save_dir, filename)

    print(f"creating image from URL...")

    try:
        response = requests.get(url, stream=True, timeout=30)

        # Check for successful response status
        if response.status_code == 200:
            with open(full_path, "wb") as f:
                for chunk in response.iter_content(chunk_size=8192):
                    f.write(chunk)
            print(f"Image successfully saved to: {full_path}")
        else:
            print(f"Failed to download image. Status code: {response.status_code}")
            try:
                print(f"API Error Response: {response.text}")
            except:
                pass

    except requests.exceptions.RequestException as e:
        print(f"An error occurred during the request: {e}")


def parse_yaml_config(file_path: str) -> Dict[str, Any]:
    """
    Parses a YAML configuration file and returns its contents as a dictionary.

    Args:
        file_path (str): The full path to the YAML configuration file.

    Returns:
        Dict[str, Any]: A dictionary containing the configuration parameters.
    """
    if not os.path.exists(file_path):
        raise FileNotFoundError(f"Configuration file not found at: {file_path}")

    try:
        with open(file_path, "r") as f:
            config = yaml.safe_load(f)
        return config
    except yaml.YAMLError as exc:
        print(f"Error parsing YAML file: {exc}")
        raise


def get_camera_matrix(image_w, image_h, fov):
    """
    Build intrinsic matrix from camera parameters.
    """
    f = image_w / (2 * math.tan(fov * math.pi / 360))
    cx = image_w / 2
    cy = image_h / 2
    K = np.array([[f, 0, cx], [0, f, cy], [0, 0, 1]])
    return K


def world_to_camera(world_point, camera_transform):
    """
    Convert world coordinates to camera coordinates.
    """
    T = camera_transform.get_matrix()
    T_inv = np.linalg.inv(T)

    # CARLA point → homogeneous
    p = np.array([world_point.x, world_point.y, world_point.z, 1.0])

    # Convert to camera coordinates (CARLA)
    p_cam = T_inv @ p  # now CARLA camera frame: X=fwd, Y=right, Z=up

    # Convert CARLA camera frame → OpenCV camera frame
    # OpenCV expects Z=fwd, X=right, Y=down
    x_carla, y_carla, z_carla, w = p_cam

    x = y_carla
    y = -z_carla
    z = x_carla

    return np.array([x, y, z, 1.0])


def camera_to_pixel(point_cam, K):
    """
    Project camera-space point into image pixel coords.
    """
    x, y, z, _ = point_cam
    if z <= 0:
        return None  # behind camera
    u = K[0, 0] * (x / z) + K[0, 2]
    v = K[1, 1] * (y / z) + K[1, 2]
    return int(u), int(v)


def connect_to_carla(host="localhost", port=2000):
    client = carla.Client(host, port)
    client.set_timeout(60.0)
    return client


def extract_geo_reference(world):
    """
    Extract the geo reference from the word


    Parameters
    ----------
    world : Carla world

    Returns
    -------
    string
        Geo reference.
    """

    xodr_content = world.get_map().to_opendrive()
    root = ET.fromstring(xodr_content)

    geo_ref = None
    header = root.find("header")
    if header is not None:
        geo = header.find("geoReference")
        if geo is not None and geo.text:
            geo_ref = geo.text.strip()

    return geo_ref


def latlon_to_world(
    lat: float, lon: float, alt: float, geo_reference: str, pgm_path: str
):
    """
    Converts geographic coordinates (lat, lon) to CARLA world coordinates (x, y, z)
    based on a given geo-reference string and EGM96 geoid file.

    Parameters:
        lat (float): Latitude in degrees
        lon (float): Longitude in degrees
        alt: orthometric altitude (meters above mean sea level)
        geo_reference (str): PROJ string defining the map projection
        pgm_path: path to egm96-15.pgm

    Returns:
        (carla_x, carla_y, carla_z): Tuple of CARLA world coordinates in meters
    """

    # --- Load offset and scale from PGM file metadata using PIL ---
    with Image.open(pgm_path) as img:
        info = img.info.get("comment", "")
        scale_match = re.search(r"Scale:\s*([-\d.]+)", info, re.IGNORECASE)
        offset_match = re.search(r"Offset:\s*([-\d.]+)", info, re.IGNORECASE)

        if scale_match and offset_match:
            scale = float(scale_match.group(1))
            offset = float(offset_match.group(1))
        else:
            # Fallback to standard EGM96-15' values if not found in comments
            # These are typical values for GeographicLib files as noted in docs
            scale = 0.003
            offset = -108.0

    logger.info(f"Geoid scale: {scale}, offset: {offset}")

    lon_wrapped = lon if lon >= 0 else lon + 360
    logger.info(f"Initial lat:{lat} lon:{lon}")
    with rasterio.open(pgm_path) as src:
        logger.info(f"Raster width:{src.width}, height:{src.height}")
        logger.info(f"Raster bounds: {src.bounds}")

        # Get row/col index safely
        row, col = src.index(lon_wrapped, lat)
        # Clamp to valid indices
        row = min(max(row, 0), src.height - 1)
        col = min(max(col, 0), src.width - 1)

        # Read the raw pixel value (it's 16-bit, so rasterio handles this)
        geoid_data = src.read(1)
        pixel_value = float(geoid_data[row, col])

        # Calculate the actual geoid height N using the correct scale and offset
        geoid_correction = offset + scale * pixel_value
        logger.info(f"Geoid correction (N) at point: {geoid_correction:.2f} m")

    # Create CRS from proj string (remains the same)
    crs = CRS.from_proj4(geo_reference)
    proj_dict = crs.to_dict()
    origin_easting = float(proj_dict.get("x_0", 0))
    origin_northing = float(proj_dict.get("y_0", 0))

    transformer = Transformer.from_crs("EPSG:4326", crs, always_xy=True)
    proj_x, proj_y = transformer.transform(lon, lat)

    carla_x = proj_x - origin_easting
    carla_y = -(proj_y - origin_northing)
    # Disable GeoID for now
    # carla_z = alt + geoid_correction
    carla_z = alt

    return carla_x, carla_y, carla_z


def parse_path_file(path):
    """
    Parse the path and make sure it exists

    Parameters:
    path (str): full path on disk

    Returns:
    str: path

    """
    if not os.path.exists(path) or not os.path.isfile(path):
        raise Exception("Invalid file: " + path)
    return path


def normalize_path(path_str: str) -> Path:
    """Normalize path"""
    return Path(path_str).expanduser().resolve()


def projection_processor(config_file: str):
    config_file = normalize_path(config_file)
    yaml_file_path = config_file
    output_folder = "/tmp"
    satellite_image_name = "real_world_frame.png"
    carla_image_name = "dt_frame.png"
    # satellite_image_path = os.path.join(output_folder, satellite_image_name)
    carla_image_path = os.path.join(output_folder, carla_image_name)
    os.makedirs(output_folder, exist_ok=True)
    config_data = parse_yaml_config(yaml_file_path)
    client = connect_to_carla(config_data["host"], config_data["port"])
    client.load_world(config_data["carla_map"])
    world = client.get_world()
    # parse geo reference
    geo_ref = extract_geo_reference(world)

    # process center camera location which is also center of salelite image
    center_lat = config_data["center_lat"]
    center_lon = config_data["center_lon"]
    center_alt = config_data["center_carla_z"]
    carla_center_x, carla_center_y, carla_center_z = latlon_to_world(
        center_lat, center_lon, center_alt, geo_ref, PGM_PATH
    )

    # Convert from lat long to carla world
    # create polygone
    polygon_world = []
    for lat, lon in config_data["path_coordinates"]:
        carla_x, carla_y, _ = latlon_to_world(lat, lon, 0, geo_ref, PGM_PATH)
        polygon_world.append(carla.Location(x=carla_x, y=carla_y, z=0))

    map_url = generate_satellite_image_url(
        center_lat=config_data["center_lat"],
        center_lon=config_data["center_lon"],
        zoom=config_data["zoom"],
        # size=config_data['size'],
        # maptype=config_data['maptype'],
        path_coordinates=config_data[
            "path_coordinates"
        ],  # Note: list of lists is converted to list of tuples internally by the function
        api_key=config_data["api_key"],
        # path_color=config_data.get('path_color', '0xFF0000FF'), # Use .get() for optional fields
        # path_weight=config_data.get('path_weight', 5)
    )
    download_and_save_image(map_url, satellite_image_name, output_folder)

    # Generate Carla frame
    blueprint_library = world.get_blueprint_library()
    # Camera settings
    image_w = int(config_data["size"].split("x")[0])
    image_h = int(config_data["size"].split("x")[1])
    fov = config_data["fov"]

    # Get camera intrinsic matrix
    K = get_camera_matrix(image_w, image_h, fov)

    # Spawn a camera
    camera_bp = blueprint_library.find("sensor.camera.rgb")
    camera_bp.set_attribute("image_size_x", str(image_w))
    camera_bp.set_attribute("image_size_y", str(image_h))
    camera_bp.set_attribute("fov", str(fov))

    # Place camera at a fixed position
    spawn_point = carla.Transform(
        carla.Location(x=carla_center_x, y=carla_center_y, z=carla_center_z),
        # satellite view pitch -90
        carla.Rotation(pitch=-90, yaw=float(config_data["yaw"]), roll=0),
    )
    camera = world.spawn_actor(camera_bp, spawn_point)

    def on_image(image):
        # global captured
        # if captured:
        #     return
        # captured = True
        # Convert CARLA image to numpy array
        array = np.frombuffer(image.raw_data, dtype=np.uint8)
        array = array.reshape((image.height, image.width, 4))[:, :, :3].copy()

        # Get camera transform (world pose)
        cam_transform = camera.get_transform()

        # Project all polygon points into the camera frame → image
        pixel_points = []
        for wp in polygon_world:
            p_cam = world_to_camera(wp, cam_transform)
            p_img = camera_to_pixel(p_cam, K)
            if p_img is not None:
                px, py = p_img
                if 0 <= px < image.width and 0 <= py < image.height:
                    pixel_points.append(p_img)

        # Draw polygon if visible
        if len(pixel_points) >= 2:
            pts_np = np.array(pixel_points, dtype=np.int32)
            cv2.polylines(
                array, [pts_np], isClosed=True, color=(255, 0, 0), thickness=3
            )

        # Save result
        cv2.imwrite(carla_image_path, array)
        logger.info("Saved {} with polygon".format(carla_image_name))

    # Start camera
    camera.listen(on_image)
    logger.info("Running for 10 seconds...")
    time.sleep(10)
    camera.stop()
    camera.destroy()
    logger.info("Done.")


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--config-file",
        type=parse_path_file,
        required=True,
        help="Path to camera spec YAML",
    )
    args = parser.parse_args()
    config_file = normalize_path(args.config_file)
    yaml_file_path = config_file
    output_folder = "/tmp"
    satellite_image_name = "real_world_frame.png"
    carla_image_name = "dt_frame.png"
    # satellite_image_path = os.path.join(output_folder, satellite_image_name)
    carla_image_path = os.path.join(output_folder, carla_image_name)
    os.makedirs(output_folder, exist_ok=True)
    config_data = parse_yaml_config(yaml_file_path)
    client = connect_to_carla(config_data["host"], config_data["port"])
    client.load_world(config_data["carla_map"])
    world = client.get_world()
    # parse geo reference
    geo_ref = extract_geo_reference(world)

    # process center camera location which is also center of salelite image
    center_lat = config_data["center_lat"]
    center_lon = config_data["center_lon"]
    center_alt = config_data["center_carla_z"]
    carla_center_x, carla_center_y, carla_center_z = latlon_to_world(
        center_lat, center_lon, center_alt, geo_ref, PGM_PATH
    )

    # Convert from lat long to carla world
    # create polygone
    polygon_world = []
    for lat, lon in config_data["path_coordinates"]:
        carla_x, carla_y, _ = latlon_to_world(lat, lon, 0, geo_ref, PGM_PATH)
        polygon_world.append(carla.Location(x=carla_x, y=carla_y, z=0))

    map_url = generate_satellite_image_url(
        center_lat=config_data["center_lat"],
        center_lon=config_data["center_lon"],
        zoom=config_data["zoom"],
        # size=config_data['size'],
        # maptype=config_data['maptype'],
        path_coordinates=config_data[
            "path_coordinates"
        ],  # Note: list of lists is converted to list of tuples internally by the function
        api_key=config_data["api_key"],
        # path_color=config_data.get('path_color', '0xFF0000FF'), # Use .get() for optional fields
        # path_weight=config_data.get('path_weight', 5)
    )
    download_and_save_image(map_url, satellite_image_name, output_folder)

    # Generate Carla frame
    blueprint_library = world.get_blueprint_library()
    # Camera settings
    image_w = int(config_data["size"].split("x")[0])
    image_h = int(config_data["size"].split("x")[1])
    fov = config_data["fov"]

    # Get camera intrinsic matrix
    K = get_camera_matrix(image_w, image_h, fov)

    # Spawn a camera
    camera_bp = blueprint_library.find("sensor.camera.rgb")
    camera_bp.set_attribute("image_size_x", str(image_w))
    camera_bp.set_attribute("image_size_y", str(image_h))
    camera_bp.set_attribute("fov", str(fov))

    # Place camera at a fixed position
    spawn_point = carla.Transform(
        carla.Location(x=carla_center_x, y=carla_center_y, z=carla_center_z),
        # satellite view pitch -90
        carla.Rotation(pitch=-90, yaw=float(config_data["yaw"]), roll=0),
    )
    camera = world.spawn_actor(camera_bp, spawn_point)

    def on_image(image):
        # global captured
        # if captured:
        #     return
        # captured = True
        # Convert CARLA image to numpy array
        array = np.frombuffer(image.raw_data, dtype=np.uint8)
        array = array.reshape((image.height, image.width, 4))[:, :, :3].copy()

        # Get camera transform (world pose)
        cam_transform = camera.get_transform()

        # Project all polygon points into the camera frame → image
        pixel_points = []
        for wp in polygon_world:
            p_cam = world_to_camera(wp, cam_transform)
            p_img = camera_to_pixel(p_cam, K)
            if p_img is not None:
                px, py = p_img
                if 0 <= px < image.width and 0 <= py < image.height:
                    pixel_points.append(p_img)

        # Draw polygon if visible
        if len(pixel_points) >= 2:
            pts_np = np.array(pixel_points, dtype=np.int32)
            cv2.polylines(
                array, [pts_np], isClosed=True, color=(255, 0, 0), thickness=3
            )

        # Save result
        cv2.imwrite(carla_image_path, array)
        logger.info("Saved {} with polygon".format(carla_image_name))

    # Start camera
    camera.listen(on_image)
    logger.info("Running for 10 seconds...")
    time.sleep(10)
    camera.stop()
    camera.destroy()
    logger.info("Done.")


# Run script
if __name__ == "__main__":
    main()
