# SPDX-FileCopyrightText: Copyright (c) 2025-2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

# Generated by Django 4.2.10 on 2024-11-19 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_sensor_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corridor',
            name='name',
            field=models.CharField(default='NEW_CORRIDOR', max_length=200),
        ),
    ]
