# SPDX-FileCopyrightText: Copyright (c) 2025-2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

# Generated by Django 4.2.10 on 2024-11-19 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_corridor_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intersection',
            name='name',
            field=models.CharField(default='ROAD_1_AND_ROAD_2', max_length=200),
        ),
    ]
