# SPDX-FileCopyrightText: Copyright (c) 2025-2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

# Generated by Django 4.2.10 on 2024-11-20 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_alter_intersection_name'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='corridor',
            unique_together={('name', 'project')},
        ),
        migrations.AlterUniqueTogether(
            name='intersection',
            unique_together={('name', 'project')},
        ),
    ]
