[metadata]
name = calibration
version = 1.0
description = A Django app to conduct Sensor Calibration.
long_description = file: README.md
url = https://www.example.com/
author = NVIDIA
author_email = arihantj@nvidia.com
license = BSD-3-Clause  # Example license
classifiers =
    'Environment :: Console'
    'Natural Language :: English'
    'Operating System :: POSIX'
    'Programming Language :: Python :: 3'
    'Topic :: Scientific/Engineering :: Artificial Intelligence'

[options]
include_package_data = True
packages = find:
scripts =
    calibration/server/entrypoint.sh
    calibration/server/manage.py
    calibration/server/deploy.sh

[entry_points]
console_scripts =
  manage = calibration.server.manage:main