# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

import importlib.util
from pathlib import Path

import pytest

from ..common import REPO_ROOT

# Helper lives in ci-vss-oss (mounted at /ci-utils in Jenkins) or optionally
# under REPO_ROOT/ci/utils for local checkouts that vendor it.
_HELPER_CANDIDATES = (
    REPO_ROOT / "ci/utils/add_generated_protobuf_headers.py",
    Path("/ci-utils/add_generated_protobuf_headers.py"),
)
HELPER_PATH = next((p for p in _HELPER_CANDIDATES if p.is_file()), None)
add_generated_protobuf_headers = None
if HELPER_PATH is not None:
    try:
        _SPEC = importlib.util.spec_from_file_location(
            "add_generated_protobuf_headers", HELPER_PATH
        )
        assert _SPEC is not None and _SPEC.loader is not None
        add_generated_protobuf_headers = importlib.util.module_from_spec(_SPEC)
        _SPEC.loader.exec_module(add_generated_protobuf_headers)
    except Exception:
        # Helper import must not break collection (e.g. bind-mount path quirks).
        add_generated_protobuf_headers = None

GENERATED_PROTOBUF_FILES = (
    REPO_ROOT / "src/protos/nv_pb2.py",
    REPO_ROOT / "docker/logstash/pb_definitions/nv_pb.rb",
)
EXPECTED_SPDX_HEADER = (
    "# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. "
    "All rights reserved.\n"
    "# SPDX-License-Identifier: Apache-2.0\n"
)


@pytest.mark.unit
@pytest.mark.parametrize("path", GENERATED_PROTOBUF_FILES)
def test_checked_in_generated_protobuf_files_have_spdx_header(path: Path):
    assert path.read_text(encoding="utf-8").startswith(EXPECTED_SPDX_HEADER)


@pytest.mark.unit
@pytest.mark.parametrize(
    "start_year,current_year,expected",
    [
        (2026, 2026, "2026"),
        (2024, 2026, "2024-2026"),
    ],
)
def test_generated_protobuf_header_year_range_policy(start_year, current_year, expected):
    if add_generated_protobuf_headers is None:
        pytest.skip("add_generated_protobuf_headers.py not available")
    assert add_generated_protobuf_headers.copyright_year_text(start_year, current_year) == expected


@pytest.mark.unit
@pytest.mark.parametrize(
    "existing_year,expected_year",
    [
        ("2024", "2024-2026"),
        ("2024-2025", "2024-2026"),
        ("2026", "2026"),
    ],
)
def test_existing_generated_protobuf_header_year_is_preserved_and_extended(
    existing_year, expected_year
):
    if add_generated_protobuf_headers is None:
        pytest.skip("add_generated_protobuf_headers.py not available")
    text = (
        "# SPDX-FileCopyrightText: Copyright (c) "
        f"{existing_year} NVIDIA CORPORATION & AFFILIATES. All rights reserved.\n"
        "# SPDX-License-Identifier: Apache-2.0\n"
        "# Generated by the protocol buffer compiler.  DO NOT EDIT!\n"
    )

    updated_text, _ = add_generated_protobuf_headers.update_existing_header(
        text,
        current_year=2026,
    )

    assert updated_text.startswith(
        "# SPDX-FileCopyrightText: Copyright (c) "
        f"{expected_year} NVIDIA CORPORATION & AFFILIATES. All rights reserved.\n"
    )
