// SPDX-FileCopyrightText: Copyright (c) 2026, NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: MIT
import { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import { createPortal } from 'react-dom';
import { Activity, ArrowDownToLine, ArrowRight, ArrowUpRight, BarChart3, Check, ChevronRight, CircleHelp, Copy, Crosshair, Database, ExternalLink, Eye, Film, FlaskConical, Focus, Layers3, LoaderCircle, Maximize, MessageSquare, Pause, Play, RefreshCw, Repeat2, ScanLine, Search, Settings2, ShieldCheck, SkipBack, SkipForward, X } from './icons';
import type { Analysis, Bottle, BottleCycle, BottleInfo, Chapter, Health, Job, QueryResult, Sample, Source } from './types';
import { api, bottleColor, clock, percent } from './api';
import Chart from './Chart';
import { CycleDetail, CycleResults, CycleSummary, cycleQuestion } from './CycleInspection';
import { SegmentationControls, FrameSynchronizedSegmentation, useSegmentation } from './Segmentation';
import LiveFilling from './LiveFilling';
import type { LiveChatContext } from './liveFrames';

const initialJob: Job = {status: 'idle', progress: 0};
const fallbackHealth: Health = {status: 'loading', vss: {configured: false, available: false, base_url: null}, analysis: initialJob};
const humanPhase = (phase?: string) => phase ? phase.replaceAll('_', ' ').replaceAll('-', ' ') : 'Outside calibrated view';
const stateDescription = (bottle: Bottle) => ({partial_view_not_validated:'The bottle bottom is outside the frame. Quantitative height is not validated in this view.',below_visible_window:'The liquid boundary is below the calibrated visible window.',at_upper_visible_limit:'At or above the upper visible reference. This does not imply a completely full bottle.',surface_occluded:'The visible liquid boundary is obstructed in this frame.',diffuse_boundary:'The liquid boundary is too diffuse for a reliable measurement.',ambiguous_color:'The image does not provide a clear liquid boundary.',out_of_frame:'The calibrated region is outside the frame.',occluded:'The calibrated region is obstructed.'}[bottle.measurement_state||''] || (bottle.level===null?'No reliable liquid boundary in this frame.':'Boundary derived from visible liquid pixels in the calibrated region.'));

function trapFocus(event: KeyboardEvent, container: HTMLElement | null) {
  if (event.key !== 'Tab' || !container) return;
  const nodes=Array.from(container.querySelectorAll<HTMLElement>('button:not(:disabled), a[href], input:not(:disabled), select:not(:disabled), video[controls], [tabindex="0"]')).filter(node=>node.getClientRects().length);
  if(!nodes.length)return;
  const first=nodes[0],last=nodes[nodes.length-1];
  if(event.shiftKey&&document.activeElement===first){event.preventDefault();last.focus();}
  else if(!event.shiftKey&&document.activeElement===last){event.preventDefault();first.focus();}
}

function Overlay({sample, source, selected, onSelect, inventory, reference}: {sample?: Sample; source: Source; selected: string | null; onSelect: (id: string) => void; inventory: BottleInfo[]; reference: number}) {
  if (!sample?.bottles.length) return null;
  const w = source.width, h = source.height;
  return <svg className="video-overlay" viewBox={`0 0 ${w} ${h}`} aria-label="Measured bottle regions and visible liquid boundaries">
    {sample.bottles.map((bottle, index) => {
      const [x, y, bw, bh] = bottle.box;
      const info = inventory.find(item => item.id === bottle.id);
      const color = bottleColor(info?.color, index);
      const selectedHere = selected === bottle.id;
      const points = (polygon: [number, number][]) => polygon.map(p => `${p[0]*w},${p[1]*h}`).join(' ');
      const label = `${bottle.label} · ${percent(bottle.level)}`;
      const labelWidth = Math.min(w*.23,Math.max(w*.092,label.length*w*.0067+w*.010));
      const labelHeight = w*.021;
      const labelX = Math.min(Math.max(w*.012,x*w),w-labelWidth-w*.012);
      const labelY = Math.max(w*.055,y*h-w*(.035+index*.029));
      const anchorX = (x+bw*.5)*w;
      return <g key={bottle.id} role="button" aria-label={`Select ${bottle.label}, visible fill height ${percent(bottle.level)}`} tabIndex={0} className="bottle-overlay" onClick={() => onSelect(bottle.id)} onKeyDown={event => {if (event.key === 'Enter' || event.key === ' ') {event.preventDefault(); onSelect(bottle.id);}}}>
        {bottle.mask.length > 2 && bottle.level !== null && <polygon points={points(bottle.mask)} fill={color} opacity={selectedHere ? '.22' : '.12'}/>}
        <rect x={x*w} y={y*h} width={bw*w} height={bh*h} rx={w*.004} fill="transparent" stroke={color} strokeWidth={w*(selectedHere ? .0018 : .001)} strokeDasharray={selectedHere ? undefined : `${w*.004} ${w*.003}`} opacity={selectedHere ? 1 : .65}/>
        {selectedHere&&bottle.measurement_box&&bottle.level!==null&&<line x1={bottle.measurement_box[0]*w} x2={(bottle.measurement_box[0]+bottle.measurement_box[2])*w} y1={(bottle.measurement_box[1]+bottle.measurement_box[3]*(1-reference))*h} y2={(bottle.measurement_box[1]+bottle.measurement_box[3]*(1-reference))*h} stroke="#efcb7a" strokeWidth={w*.0013} strokeDasharray={`${w*.003} ${w*.002}`}/>}
        {bottle.surface.length > 1 && bottle.level !== null && <polyline points={points(bottle.surface)} fill="none" stroke={color} strokeWidth={w*.0022} strokeLinecap="round"/>}
        <path d={`M${Math.min(labelX+labelWidth-w*.007,Math.max(labelX+w*.007,anchorX))},${labelY+labelHeight} L${anchorX},${y*h}`} stroke={color} strokeWidth={w*.0011} fill="none"/>
        <rect x={labelX} y={labelY} width={labelWidth} height={labelHeight} rx={w*.003} fill={color}/>
        <text x={labelX+w*.005} y={labelY+labelHeight*.72} fontSize={w*.011} fill="#10200b" fontWeight="700" fontFamily="monospace">{label}</text>
      </g>;
    })}
  </svg>;
}

function BottleFocus({video, bottle, time}: {video: HTMLVideoElement | null; bottle?: Bottle; time: number}) {
  const canvas = useRef<HTMLCanvasElement>(null);
  useEffect(() => {
    const target = canvas.current;
    if (!target || !video || !bottle) return;
    const context = target.getContext('2d');
    if (!context) return;
    let frame = 0;
    let videoFrame = 0;
    const draw = () => {
      if(video.readyState<2||video.seeking||!video.videoWidth||!video.videoHeight)return;
      const [x,y,w,h] = bottle.box;
      const pad = .018;
      const sx = Math.max(0,x-pad)*video.videoWidth, sy = Math.max(0,y-pad)*video.videoHeight;
      const sw = Math.min(video.videoWidth-sx,(w+pad*2)*video.videoWidth), sh = Math.min(video.videoHeight-sy,(h+pad*2)*video.videoHeight);
      if(sw<=0||sh<=0)return;
      if(target.width!==240||target.height!==240){target.width=240;target.height=240;}
      context.fillStyle = '#141914'; context.fillRect(0,0,240,240);
      const scale = Math.min(240/sw,240/sh);
      context.drawImage(video,sx,sy,sw,sh,(240-sw*scale)/2,(240-sh*scale)/2,sw*scale,sh*scale);
    };
    const refresh = () => {cancelAnimationFrame(frame);frame=requestAnimationFrame(draw);};
    video.addEventListener('seeked',refresh);
    video.addEventListener('loadeddata',refresh);
    video.addEventListener('canplay',refresh);
    window.addEventListener('resize',refresh);
    const resizeObserver=new ResizeObserver(refresh);
    resizeObserver.observe(target);
    // A React time update may precede decoding. Draw only after an actual
    // media-frame event, and also refresh an already-decoded paused frame.
    refresh();
    if('requestVideoFrameCallback' in video)videoFrame=video.requestVideoFrameCallback(refresh);
    return()=>{cancelAnimationFrame(frame);if(videoFrame)video.cancelVideoFrameCallback(videoFrame);video.removeEventListener('seeked',refresh);video.removeEventListener('loadeddata',refresh);video.removeEventListener('canplay',refresh);window.removeEventListener('resize',refresh);resizeObserver.disconnect();};
  }, [video,bottle,time]);
  return <canvas ref={canvas} className="focus-canvas" aria-label="Magnified crop of selected bottle from the current source frame"/>;
}

function EvidenceDrawer({range, source, onClose, seek}: {range: {start: number; end: number; label: string}; source: Source; onClose: () => void; seek: (t: number) => void}) {
  const [start,setStart] = useState(range.start), [end,setEnd] = useState(range.end), [copied,setCopied] = useState(false), [copyError,setCopyError] = useState('');
  const link = `/filling/api/evidence?start=${start.toFixed(2)}&end=${end.toFixed(2)}&source_id=${encodeURIComponent(source.id)}`;
  const close = useRef<HTMLButtonElement>(null);
  useEffect(() => {const previous = document.activeElement as HTMLElement | null; close.current?.focus(); const listener = (event: KeyboardEvent) => {if(event.key==='Escape') onClose();trapFocus(event,document.querySelector('.evidence-drawer'));}; document.addEventListener('keydown',listener); return () => {document.removeEventListener('keydown',listener); previous?.focus();};},[onClose]);
  const copy = async () => {try {await navigator.clipboard.writeText(`${source.name} · source ${clock(start,true)}–${clock(end,true)} · SHA-256 ${source.sha256}\n${new URL(link,window.location.origin)}`);setCopied(true);setCopyError('');}catch{setCopyError('Clipboard unavailable. Use the download or open link.');}};
  return createPortal(<div className="vss-filling vss-filling-portal"><div className="drawer-backdrop" onClick={onClose}><section className="evidence-drawer" role="dialog" aria-modal="true" aria-labelledby="evidence-title" onClick={event => event.stopPropagation()}><div className="drawer-header"><div><span className="eyebrow">VSS SOURCE EVIDENCE</span><h2 id="evidence-title">Video evidence</h2></div><button ref={close} className="icon-button" onClick={onClose} aria-label="Close evidence"><X size={20}/></button></div><p className="muted">{range.label}</p><video key={link} className="evidence-video" src={link} controls preload="metadata"/><div className="evidence-times"><label>Start · source seconds<input aria-label="Evidence start in source seconds" type="number" min={0} max={end-.1} step=".1" value={start} onChange={e=>setStart(Math.max(0,Math.min(end-.1,Number(e.target.value))))}/></label><ArrowRight size={18}/><label>End · source seconds<input aria-label="Evidence end in source seconds" type="number" min={start+.1} max={source.duration} step=".1" value={end} onChange={e=>setEnd(Math.min(source.duration,Math.max(start+.1,Number(e.target.value))))}/></label></div><div className="evidence-meta"><span>Original source</span><strong>{source.name}</strong><span>Source range</span><strong>{clock(start,true)} — {clock(end,true)}</strong><span>Provenance</span><strong className="hash" title={source.sha256}>{source.sha256.slice(0,20)}…</strong></div><div className="button-row"><a className="button primary" href={link} download={`vss-evidence-${start.toFixed(1)}-${end.toFixed(1)}.mp4`}><ArrowDownToLine size={16}/>Download clip</a><button className="button secondary" onClick={copy}>{copied?<Check size={16}/>:<Copy size={16}/>} {copied?'Copied':'Copy citation'}</button></div>{copyError&&<p className="error-text">{copyError}</p>}<button className="text-button" onClick={()=>{seek(start);onClose();}}>Open this moment in source <ArrowUpRight size={14}/></button><div className="info-note"><ShieldCheck size={17}/><p>Extracted from the original recording. Timestamps refer to the source video. This clip is evidence, not a new VSS incident.</p></div></section></div></div>,document.body);
}

type VssSource = {id:string;name:string;sensor_id?:string;stream_id?:string;state?:string;status?:string;type?:string;is_main?:boolean;has_timeline?:boolean;error?:string};
type Props = {onLiveChatContextChange?:(context:LiveChatContext|null)=>void;sourceRequest?:{sensor_id?:string;stream_id?:string;name?:string;request_id:number}|null;theme?:'light'|'dark';isActive?:boolean;submitChatMessage?:(message:string)=>void;addChatQueryContext?:(context:{id:string;label:string;contextType:string;data:Record<string,unknown>})=>void};
function RecordingAnalysis({theme='dark',isActive=true,sourceRequest,submitChatMessage,addChatQueryContext}:Props) {
  const [source,setSource] = useState<Source|null>(null), [health,setHealth] = useState<Health>(fallbackHealth), [job,setJob] = useState<Job>(initialJob), [analysis,setAnalysis] = useState<Analysis|null>(null);
  const [error,setError] = useState(''), [time,setTime] = useState(24), [playing,setPlaying] = useState(false), [rate,setRate] = useState(1), [overlays,setOverlays] = useState(true), [loop,setLoop] = useState(false), [selected,setSelected] = useState<string|null>(null), [comparison,setComparison] = useState<string[]>([]), [reference,setReference] = useState(.75), [evidence,setEvidence] = useState<{start:number;end:number;label:string}|null>(null);
  const [question,setQuestion] = useState(''), [queryResult,setQueryResult] = useState<QueryResult|null>(null), [queryLoading,setQueryLoading] = useState(false), [queryError,setQueryError] = useState(''), [showInfo,setShowInfo] = useState(false);
  const video = useRef<HTMLVideoElement>(null), player = useRef<HTMLDivElement>(null), sceneRef = useRef<string|null>(null), analysisRef = useRef<Analysis|null>(null);
  const [loopChapter,setLoopChapter] = useState<Chapter|null>(null);
  const segmentation = useSegmentation(source, time, isActive, analysis?.provenance?.segmentation_cache_key);
  useEffect(() => { if (segmentation.result) setOverlays(false); }, [segmentation.result]);
  const fetchingResult = useRef(false);
  const sourceRef=useRef<Source|null>(null);
  useEffect(()=>{sourceRef.current=source;},[source]);
  const [vssSources,setVssSources]=useState<VssSource[]>([]),[sourceChoice,setSourceChoice]=useState(''),[selecting,setSelecting]=useState(false),[selectionNotice,setSelectionNotice]=useState('');
  const selectionBusy=useRef(false);
  const loadSources=useCallback(async()=>{try{const listing=await api<{available:boolean;sources:VssSource[];reason?:string}>('/filling/api/vss/sources');setVssSources(listing.sources||[]);if(!listing.available)setSelectionNotice(listing.reason||'VIOS source discovery is unavailable.');else setSelectionNotice('');}catch(e){setSelectionNotice((e as Error).message);}},[]);
  const selectVssSource=useCallback(async(choice:VssSource)=>{
    if(selectionBusy.current)return;
    selectionBusy.current=true;setSelecting(true);setError('');setSelectionNotice('Retrieving the complete recording from VIOS and verifying its identity. This can take a minute or two.');
    video.current?.pause();setEvidence(null);setQueryResult(null);setQueryError('');setQuestion('');setLoop(false);setLoopChapter(null);setSource(null);sourceRef.current=null;setAnalysis(null);analysisRef.current=null;
    try{const selectedSource=await api<Source>('/filling/api/vss/select',{method:'POST',body:JSON.stringify({...(choice.sensor_id?{sensor_id:choice.sensor_id}:{}),...(choice.stream_id?{stream_id:choice.stream_id}:choice.sensor_id?{}:{sensor_id:choice.id})})});sourceRef.current=selectedSource;setSource(selectedSource);setSourceChoice(choice.id);setTime(Math.min(24,selectedSource.duration));setSelected(null);setComparison([]);sceneRef.current=null;setJob(await api<Job>('/filling/api/analysis'));setSelectionNotice('VIOS recording selected. Analyze it to compute visible-height measurements, or review its matching saved analysis.');setAnalysis(null);analysisRef.current=null;}catch(e){setError((e as Error).message);setSelectionNotice('Selection did not complete. Choose a registered recording; no local-video fallback is used.');}finally{selectionBusy.current=false;setSelecting(false);}
  },[]);
  useEffect(()=>{void loadSources();},[loadSources]);
  useEffect(()=>{if(!isActive)video.current?.pause();},[isActive]);
  const consumedSourceRequest=useRef<number|null>(null);
  useEffect(()=>{if(!sourceRequest||selecting||consumedSourceRequest.current===sourceRequest.request_id)return;consumedSourceRequest.current=sourceRequest.request_id;void loadSources();void selectVssSource({id:sourceRequest.stream_id||sourceRequest.sensor_id!,name:sourceRequest.name||'Selected VIOS recording',sensor_id:sourceRequest.sensor_id,stream_id:sourceRequest.stream_id});},[sourceRequest,selecting,loadSources,selectVssSource]);
  const askAgent=()=>{if(!source?.stream_id||!submitChatMessage)return;const prompt=question.trim()||(isCycleAnalysis?cycleQuestion:'Compare the measured bottles in this filling shot and show source evidence.');const context={sensor_id:source.sensor_id,stream_id:source.stream_id,source_sha256:source.sha256,source_time_seconds:Number(time.toFixed(2)),scene_id:sceneId,reference_level:isCycleAnalysis?selectedCycle?.reference_level:reference,bottle_id:selected,analysis_kind:analysis?.analysis_kind};addChatQueryContext?.({id:`filling:${source.stream_id}:${time.toFixed(2)}`,label:`Filling measurements · ${source.name} · ${clock(time)}`,contextType:'filling-measurements',data:context});submitChatMessage(`${prompt}\nUse the vss-inspect-filling skill and the vss filling CLI through the OpenClaw vss_cli tool. Query the currently selected VIOS recording with vss filling query --stream-id <UUID> --question <question> --scene-id <scene>${isCycleAnalysis?'':' --reference-percent <reference percent>'}; use the exact values below. Return the real video_evidences supplied by the CLI, not constructed links. Stream UUID: ${source.stream_id}; source offset: ${time.toFixed(2)} seconds; scene: ${sceneId||'outside measurement view'}; ${isCycleAnalysis?'Use the analysis reference without a reference-percent override.':`visible-height reference: ${Math.round(reference*100)}%.`} ${isCycleAnalysis?'Inspect completed bottle cycles using measured height rise and stability; do not claim nozzle flow or exact transfer completion. The final-height reference is camera-specific, and overflow uses separate exterior-liquid evidence. ':''}Measurement algorithm: ${analysis?.algorithm||'not available'}. ${neuralMeasurements?'Heights and underfill use RF-DETR masks; overflow uses a separate exterior-color check. ':''}Report measured values and uncertainty, and cite their source offsets. Visible height is not volume.`);};

  useEffect(()=>{if(!showInfo)return;const previous=document.activeElement as HTMLElement|null;const timer=setTimeout(()=>document.querySelector<HTMLButtonElement>('.info-dialog button')?.focus(),0);const listener=(event:KeyboardEvent)=>{if(event.key==='Escape')setShowInfo(false);trapFocus(event,document.querySelector('.info-dialog'));};document.addEventListener('keydown',listener);return()=>{clearTimeout(timer);document.removeEventListener('keydown',listener);previous?.focus();};},[showInfo]);
  useEffect(() => {analysisRef.current=analysis;},[analysis]);
  useEffect(() => {
    let mounted=true;
    const initial = async () => {
      const results=await Promise.allSettled([api<Source>('/filling/api/source'),api<Health>('/filling/api/health')]);
      if(!mounted)return;
      if(results[0].status==='fulfilled'){setSource(results[0].value);setSourceChoice(results[0].value.stream_id||results[0].value.sensor_id||'');setError('');}else setSelectionNotice('Choose a registered VIOS recording above to begin.');
      if(results[1].status==='fulfilled'){setHealth(results[1].value);setJob(results[1].value.analysis);}else setError(previous=>previous||'The analysis service is unavailable.');
    };
    void initial();
    const interval=setInterval(async()=>{try{const h=await api<Health>('/filling/api/health');if(mounted){setHealth(h);setJob(h.analysis);}}catch{if(mounted)setHealth(h=>({...h,status:'unavailable'}));}},8000);
    return()=>{mounted=false;clearInterval(interval);};
  },[]);
  useEffect(()=>{
    let mounted=true;
    const poll=async()=>{try{const next=await api<Job>('/filling/api/analysis');if(!mounted)return;setJob(next);if(!selectionBusy.current){try{const actual=await api<Source>('/filling/api/source');if(!mounted)return;if(actual.id!==sourceRef.current?.id){video.current?.pause();sourceRef.current=actual;setSource(actual);setSourceChoice(actual.stream_id||actual.sensor_id||'');setTime(Math.min(24,actual.duration));setEvidence(null);setQueryResult(null);setQueryError('');setQuestion('');setLoop(false);setLoopChapter(null);setAnalysis(null);analysisRef.current=null;setSelected(null);setComparison([]);sceneRef.current=null;setSelectionNotice('Selected VIOS recording refreshed from the shared VSS tool state.');}}catch{/* No selected recording or a selection is in progress. */}}if(next.status==='complete'&&!selectionBusy.current&&!analysisRef.current&&!fetchingResult.current){fetchingResult.current=true;try{const result=await api<Analysis>('/filling/api/analysis/result');if(mounted&&sourceRef.current&&result.source_sha256===sourceRef.current.sha256){setAnalysis(result);setError('');}}catch(e){if(mounted)setError((e as Error).message);}finally{fetchingResult.current=false;}}}catch(e){if(mounted)setError((e as Error).message);}};
    void poll();const interval=setInterval(poll,2000);return()=>{mounted=false;clearInterval(interval);};
  },[]);
  const nearest = useMemo(()=>{
    if(!analysis?.samples.length)return undefined;
    let low=0,high=analysis.samples.length-1;
    while(low<high){const mid=Math.floor((low+high)/2);if(analysis.samples[mid].t<time)low=mid+1;else high=mid;}
    const before=analysis.samples[Math.max(0,low-1)],after=analysis.samples[low];
    const found=Math.abs(before.t-time)<Math.abs(after.t-time)?before:after;
    const sampleChapter=source?.chapters.find(c=>found.t>=c.start&&found.t<c.end);
    const playbackChapter=source?.chapters.find(c=>time>=c.start&&time<c.end);
    if(sampleChapter?.id!==playbackChapter?.id)return undefined;
    return Math.abs(found.t-time)<=Math.max(.55,1.5/analysis.sample_fps)?found:undefined;
  },[analysis,time,source]);
  const isCycleAnalysis=analysis?.analysis_kind==='bottle-cycles';
  const neuralMeasurements=analysis?.algorithm==='rfdetr-mask-cycle-v2' && analysis?.quality.measurement_engine==='rfdetr';
  const unifiedAnalysis=source?.analysis_kind==='bottle-cycles' || isCycleAnalysis;
  const analysisMethod=neuralMeasurements?'RF-DETR mask-derived height':analysis?'Legacy calibrated visible boundary':'Not analyzed';
  const cycles=useMemo(()=>[...(analysis?.cycles||[])].sort((a,b)=>a.start_time-b.start_time),[analysis]);
  const currentCycle=cycles.find(cycle=>time>=cycle.start_time&&time<=cycle.end_time);
  const selectedCycle=cycles.find(cycle=>cycle.id===selected)??currentCycle??cycles[0];
  const sceneId=isCycleAnalysis?'single-station':nearest?.scene_id??null;
  const sceneBottles=useMemo(()=>isCycleAnalysis?analysis?.bottles.filter(b=>b.id===selectedCycle?.id)||[]:analysis?.bottles.filter(b=>b.scene_id===sceneId).slice(0,3)||[],[analysis,sceneId,isCycleAnalysis,selectedCycle?.id]);
  const sceneSamples=useMemo(()=>analysis?.samples.filter(s=>s.scene_id===sceneId)||[],[analysis,sceneId]);
  useEffect(()=>{if(isCycleAnalysis){if(currentCycle)setSelected(currentCycle.id);return;}if(sceneId!==sceneRef.current){sceneRef.current=sceneId;setSelected(sceneBottles[0]?.id??null);setComparison(sceneBottles.map(b=>b.id));}},[sceneId,sceneBottles,isCycleAnalysis,currentCycle?.id]);
  const selectedBottle=nearest?.bottles.find(b=>b.id===(isCycleAnalysis?selectedCycle?.id:selected));
  const chartBottles=isCycleAnalysis?sceneBottles:sceneBottles.filter(b=>comparison.includes(b.id));
  const currentChapter=source?.chapters.find(c=>time>=c.start&&time<c.end);
  const seek=useCallback((t:number)=>{if(video.current){video.current.currentTime=Math.max(0,Math.min(source?.duration??t,t));setTime(video.current.currentTime);}},[source]);
  const jumpChapter=(chapter:Chapter)=>{seek(chapter.start+.05);setLoopChapter(chapter);};
  const togglePlay=()=>{if(!video.current)return;if(video.current.paused){void video.current.play().catch(()=>setError('Playback could not start. Try the play button again.'));}else video.current.pause();};
  const openEvidence=(t=time,label='Selected source moment')=>{if(source){video.current?.pause();setEvidence({start:Math.max(0,Math.round((t-2)*10)/10),end:Math.min(source.duration,Math.round((t+4)*10)/10),label});}};
  const selectCycle=(cycle:BottleCycle)=>{setSelected(cycle.id);setLoopChapter({id:cycle.id,label:cycle.label,start:cycle.start_time,end:cycle.end_time,kind:'reference',description:cycle.reason});seek(cycle.measurement_time??cycle.overflow_time??cycle.evidence_start);};
  const openCycleEvidence=(cycle:BottleCycle)=>{if(!source)return;video.current?.pause();setSelected(cycle.id);setEvidence({start:Math.max(0,cycle.evidence_start),end:Math.min(source.duration,cycle.evidence_end),label:`${cycle.label} · ${cycle.reason}`});};
  const closeEvidence=useCallback(()=>setEvidence(null),[]);
  const startAnalysis=async(force=false)=>{setError('');try{const next=await api<Job>('/filling/api/analysis',{method:'POST',body:JSON.stringify({force,source_id:source?.id})});setAnalysis(null);analysisRef.current=null;setJob(next);}catch(e){setError((e as Error).message);}};
  const ask=async(text=question)=>{if(!text.trim()||queryLoading)return;setQuestion(text);setQueryLoading(true);setQueryError('');try{setQueryResult(await api<QueryResult>('/filling/api/query',{method:'POST',body:JSON.stringify({question:text,reference_level:isCycleAnalysis?undefined:reference,scene_id:sceneId||undefined})}));}catch(e){setQueryError((e as Error).message);}finally{setQueryLoading(false);}};
  const crossings=useMemo(()=>sceneBottles.map(b=>{const index=sceneSamples.findIndex(s=>{const item=s.bottles.find(v=>v.id===b.id);return item?.level!==null&&item?.level!==undefined&&item.level>=reference;});const row=sceneSamples[index];const firstReadable=sceneSamples.findIndex(s=>s.bottles.some(v=>v.id===b.id&&v.level!==null));const previous=sceneSamples[index-1]?.bottles.find(v=>v.id===b.id);const alreadyAbove=index>=0&&index===firstReadable;const afterGap=index>=0&&!alreadyAbove&&(previous?.level===null||previous?.level===undefined);return{id:b.id,t:row?.t,uncertain:alreadyAbove||afterGap,note:alreadyAbove?'Already at or above the reference on the first readable sample; crossing time unknown.':afterGap?'First observed at or above after unreadable frames; crossing time unknown.':'First observed sample at or above the reference; not an interpolated crossing time.'};}),[sceneBottles,sceneSamples,reference]);
  const measuredCount=nearest?.bottles.filter(b=>b.level!==null).length??0;
  const progress=job.progress>1?job.progress:job.progress*100;
  return <div className={`vss-filling ${theme==='light'?'vss-filling-light':''}`}>
      <main>
        <section className="native-heading"><div><h2>Filling analysis</h2><p>{neuralMeasurements?'RF-DETR fill-height measurements and bottle inspection, with VSS source evidence.':isCycleAnalysis?'Bottle-by-bottle inspection of a VSS recording, with final-height measurements and video evidence.':'Visible-height measurements for a recording selected from VSS Video Management.'}</p></div><div className="heading-actions"><button className="button secondary" onClick={askAgent} disabled={!source?.stream_id||!submitChatMessage}><MessageSquare size={15}/>Ask VSS Agent</button><a className={`button secondary ${!analysis?'disabled':''}`} href="/filling/api/export.csv" download aria-disabled={!analysis} onClick={e=>{if(!analysis)e.preventDefault();}}><ArrowDownToLine size={15}/>Export measurements</a><button className="button secondary compact" onClick={()=>startAnalysis(!!analysis)} disabled={!source||selecting||job.status==='running'}>{job.status==='running'?<LoaderCircle className="spin" size={15}/>:<RefreshCw size={15}/>} {analysis?'Reanalyze':job.status==='running'?'Analyzing':'Analyze recording'}</button></div></section>
        <section className="native-source-selector"><div className="native-source-control"><label htmlFor="vss-filling-source">VIOS recording</label><select id="vss-filling-source" value={sourceChoice} disabled={selecting} onChange={e=>setSourceChoice(e.target.value)}><option value="">Select a registered source…</option>{vssSources.map(item=><option key={item.id} value={item.id}>{item.name}{item.has_timeline===false?' · no recording timeline':''}</option>)}</select><button className="button primary" disabled={!sourceChoice||selecting} onClick={()=>{const item=vssSources.find(s=>s.id===sourceChoice);if(item)void selectVssSource(item);}}>{selecting?<LoaderCircle className="spin" size={15}/>:<Database size={15}/>} {selecting?'Loading from VIOS':'Load recording'}</button><button className="icon-button" aria-label="Refresh VIOS sources" title="Refresh VIOS sources" onClick={()=>void loadSources()} disabled={selecting}><RefreshCw size={15}/></button></div>{selectionNotice&&<p role="status">{selectionNotice}</p>}{source?.stream_id&&<div className="native-source-identity"><ShieldCheck size={13}/><span>VSS stream {source.stream_id}</span><span>·</span><span>Original source offsets</span></div>}</section>
        {error&&<div className="error-banner" role="alert"><span>{error}</span><button className="text-button" onClick={()=>window.location.reload()}>Retry <RefreshCw size={14}/></button></div>}
        {job.status==='running'&&<div className="analysis-banner" role="status"><LoaderCircle className="spin" size={16}/><span>{unifiedAnalysis?'Running RF-DETR and deriving bottle measurements from the recording':'Measuring visible liquid boundaries from the recording'}</span><div className="analysis-progress"><i style={{width:`${Math.max(1,Math.min(100,progress))}%`}}/></div><strong>{Math.round(progress)}%</strong></div>}
        {job.status==='error'&&<div className="error-banner" role="alert"><span>Analysis failed: {job.error||'Unknown analysis error'}</span><button className="text-button" onClick={()=>startAnalysis(true)}>Try again</button></div>}
        {isCycleAnalysis&&<CycleSummary cycles={cycles} neuralMeasurements={neuralMeasurements}/>}
        <div className="workspace-grid" id="monitor">
          <section className="panel video-panel"><div className="panel-topline"><div className="panel-title"><span className="status-dot lime"/><h2>Filling station</h2><span className="pill subtle">{analysis?'ANALYZED REPLAY':'SOURCE REPLAY'}</span></div>{!neuralMeasurements&&<button className={`text-button overlay-toggle ${overlays?'enabled':''}`} onClick={()=>setOverlays(v=>!v)} aria-pressed={overlays}><Layers3 size={15}/><span>{neuralMeasurements?'Measurement guides':'Calibrated guides'}</span><span className={`mini-toggle ${overlays?'on':''}`}/></button>}</div>
            <div className="video-stage" ref={player} style={{aspectRatio:source?`${source.width}/${source.height}`:'1.5889'}}>
              {source?<><video key={source.id} ref={video} src={source.media_url} preload="auto" playsInline muted onLoadedMetadata={()=>{if(video.current)video.current.currentTime=Math.min(24,source.duration);}} onTimeUpdate={()=>{const v=video.current;if(!v)return;if(loop&&loopChapter&&v.currentTime>=loopChapter.end){v.currentTime=loopChapter.start;}setTime(v.currentTime);}} onPlay={()=>setPlaying(true)} onPause={()=>setPlaying(false)} onEnded={()=>{if(loop&&video.current){video.current.currentTime=loopChapter?.start??0;void video.current.play();}else setPlaying(false);}} onError={()=>setError('The VIOS recording could not be loaded. Check the filling-analysis and VIOS services.')} onClick={togglePlay}/>{!neuralMeasurements&&overlays&&<Overlay sample={nearest} source={source} selected={selected} onSelect={setSelected} inventory={analysis?.bottles||[]} reference={isCycleAnalysis?selectedCycle?.reference_level??reference:reference}/>}<FrameSynchronizedSegmentation video={video} result={segmentation.result} source={source} showBottle={segmentation.showBottle} showLiquid={segmentation.showLiquid} active={isActive}/><div className="video-top-left"><span className="video-chip"><span className="status-dot lime"/> RECORDED SOURCE</span><span className="source-size">{source.width} × {source.height}</span></div><div className="video-top-right"><span className="video-time">{clock(time,true)}</span></div><div className="video-bottom-note"><ScanLine size={14}/><span>{sceneId?`${measuredCount} visible measurements · ${humanPhase(nearest?.phase)}`:'No active measurement region in this shot'}</span></div>{!playing&&<button className="big-play" onClick={togglePlay} aria-label="Play source video"><Play size={24} fill="currentColor"/></button>}</>:<div className="video-placeholder"><Film size={36}/><span>{selecting?'Retrieving your VIOS recording…':'Select a VIOS recording above'}</span></div>}
            </div>
            <div className="player-controls"><button className="icon-button play-control" onClick={togglePlay} disabled={!source} aria-label={playing?'Pause video':'Play video'}>{playing?<Pause size={18} fill="currentColor"/>:<Play size={18} fill="currentColor"/>}</button><button className="icon-button skip-control" onClick={()=>seek(time-5)} aria-label="Back five seconds"><SkipBack size={16}/></button><div className="player-time"><strong>{clock(time)}</strong><span>/ {clock(source?.duration??0)}</span></div><input className="seek-slider" aria-label="Source video position" type="range" min={0} max={source?.duration??108} step=".05" value={time} onChange={e=>seek(Number(e.target.value))} style={{'--seek':`${time/(source?.duration||108)*100}%`} as React.CSSProperties}/><button className="icon-button skip-control" onClick={()=>seek(time+5)} aria-label="Forward five seconds"><SkipForward size={16}/></button><select className="rate-select" aria-label="Playback speed" value={rate} onChange={e=>{const n=Number(e.target.value);setRate(n);if(video.current)video.current.playbackRate=n;}}>{[.25,.5,1,1.5,2].map(r=><option key={r} value={r}>{r}×</option>)}</select><button className={`icon-button ${loop?'selected':''}`} aria-label="Loop current chapter" title={loopChapter?`Loop ${loopChapter.label}`:'Loop current chapter'} aria-pressed={loop} onClick={()=>{setLoop(v=>!v);if(!loopChapter&&currentChapter)setLoopChapter(currentChapter);}}><Repeat2 size={17}/></button><button className="icon-button" onClick={()=>{void player.current?.requestFullscreen().catch(()=>setError('Fullscreen is unavailable in this browser.'));}} aria-label="Fullscreen video"><Maximize size={16}/></button></div>
            <div className="video-footer"><div><Film size={14}/><span>{source?.name??'Loading recording'}</span><span className="footer-dot">·</span><span>Original source time</span></div><button className="text-button" onClick={()=>openEvidence()} disabled={!source}>Open evidence <ArrowUpRight size={14}/></button></div>
            <SegmentationControls state={segmentation} source={source} unified={unifiedAnalysis} neuralMeasurements={neuralMeasurements}/>
          </section>
          {isCycleAnalysis?<CycleDetail neuralMeasurements={neuralMeasurements} cycle={selectedCycle} currentLevel={selectedBottle?.level??null} evidence={openCycleEvidence} askAgent={source?.stream_id&&submitChatMessage?askAgent:undefined}/>:<section className="panel tracking-panel"><div className="panel-topline"><div className="panel-title"><Crosshair size={16}/><h2>Bottle measurements</h2></div><span className="small-mono">{sceneBottles.length.toString().padStart(2,'0')} REGIONS</span></div><div className="tracking-intro"><span className="eyebrow">VISIBLE FILL HEIGHT</span><span className="small-note">Relative to calibrated region</span></div>
            <div className="bottle-list">{sceneBottles.length?sceneBottles.map((info,index)=>{const bottle=nearest?.bottles.find(b=>b.id===info.id);const color=bottleColor(info.color,index);return <button key={info.id} className={`bottle-row ${selected===info.id?'active':''}`} onClick={()=>setSelected(info.id)} style={{'--bottle-color':color} as React.CSSProperties}><div className="bottle-icon"><FlaskConical size={23}/></div><div className="bottle-info"><div><strong>{info.label}</strong><span className="bottle-state">{bottle?.level===null||!bottle?'Unreadable':bottle.level>=.975?'Upper reference':'Measured'}</span></div><div className="level-track"><i style={{width:`${(bottle?.level??0)*100}%`}}/></div><span className="confidence-label">{bottle?.level!==null&&bottle?`Boundary fit ${Math.round(bottle.confidence*100)}/100`:bottle?stateDescription(bottle):'No reliable boundary at this moment'}</span></div><strong className="bottle-level">{percent(bottle?.level??null)}</strong><ChevronRight size={14}/></button>;}):<div className="tracking-empty"><ScanLine size={29}/><h3>{analysis?'Tracking pauses between calibrated shots':'Measurements are not ready yet'}</h3><p>{analysis?'Choose a filling chapter below. Bottle identities reset with each camera view.':'Analyze the source to reveal measured liquid boundaries and progress curves.'}</p>{source&&!analysis&&job.status!=='running'&&<button className="button primary" onClick={()=>startAnalysis()}>Analyze video <ArrowRight size={15}/></button>}</div>}</div>
            <div className="focus-block"><div className="focus-header"><Focus size={14}/><span>Selected bottle</span><strong>{selectedBottle?.label??'—'}</strong></div>{selectedBottle?<div className="focus-content"><BottleFocus video={video.current} bottle={selectedBottle} time={time}/><div><span className="eyebrow">CURRENT PHASE</span><h3>{humanPhase(nearest?.phase)}</h3><p>{stateDescription(selectedBottle)}</p><button className="text-button" onClick={()=>openEvidence(time,`${selectedBottle.label} · ${percent(selectedBottle.level)} visible fill height`)}>View source evidence <ArrowUpRight size={14}/></button></div></div>:<div className="focus-empty">Select a measured bottle in the video or list.</div>}</div>
            <div className="measurement-note"><ShieldCheck size={15}/><p>Visible height, not liquid volume. Measurements apply to calibrated shots only.</p></div>
          </section>}
        </div>
        <div className="insights-grid">
          <section className="panel comparison-panel" id="compare"><div className="panel-topline"><div className="panel-title"><BarChart3 size={16}/><h2>{isCycleAnalysis?`${selectedCycle?.label??'Bottle'} fill progress`:'Compare the fill'}</h2><span className="pill subtle">{sceneId?'CURRENT SHOT':'SELECT A SHOT'}</span></div><span className="small-note">Click graph to seek</span></div><div className="comparison-body"><div className="chart-area"><div className="chart-legend">{sceneBottles.map((b,index)=><button key={b.id} className={`legend-chip ${isCycleAnalysis||comparison.includes(b.id)?'':'inactive'}`} onClick={()=>{if(!isCycleAnalysis)setComparison(ids=>ids.includes(b.id)?ids.filter(id=>id!==b.id):[...ids,b.id]);}} aria-pressed={isCycleAnalysis||comparison.includes(b.id)}><span style={{background:bottleColor(b.color,index)}}/>{b.label}{comparison.includes(b.id)&&<Check size={11}/>}</button>)}<span className="axis-title">HEIGHT %</span></div><Chart analysis={analysis} bottles={chartBottles} sceneId={sceneId} currentTime={time} reference={isCycleAnalysis?selectedCycle?.reference_level??reference:reference} onReference={setReference} seek={seek} timeRange={isCycleAnalysis&&selectedCycle?{start:selectedCycle.start_time,end:selectedCycle.end_time}:undefined} referenceReadOnly={isCycleAnalysis}/></div>{!isCycleAnalysis&&<div className="crossing-panel"><span className="eyebrow">FIRST OBSERVED AT</span><h3>{Math.round(reference*100)}% reference</h3><p>First source sample observed at or above your reference.</p>{sceneBottles.map((b,index)=>{const crossing=crossings.find(c=>c.id===b.id);return <button className="crossing-row" key={b.id} title={crossing?.t===undefined?'No readable sample was observed at or above this reference.':crossing.note} aria-label={`${b.label}: ${crossing?.t===undefined?'Not observed':`${clock(crossing.t,true)}. ${crossing.note}`}`} disabled={crossing?.t===undefined} onClick={()=>crossing?.t!==undefined&&seek(crossing.t)}><span className="legend-dot" style={{background:bottleColor(b.color,index)}}/><span>{b.label}</span><strong>{crossing?.t===undefined?'Not observed':`${clock(crossing.t,true)}${crossing.uncertain?'*':''}`}</strong>{crossing?.t!==undefined&&<ArrowUpRight size={13}/>}</button>;})}{!sceneBottles.length&&<span className="small-note">No calibrated shot selected</span>}<div className="small-note crossing-footnote">Sampled observations, not exact crossing times. * Already above at the first readable sample or after a gap; crossing unknown.</div></div>}</div></section>
          <section className="panel source-panel"><div className="panel-topline"><div className="panel-title"><Database size={16}/><h2>Source & provenance</h2></div><button className="icon-button" onClick={()=>setShowInfo(true)} aria-label="View source and analysis details"><ArrowUpRight size={15}/></button></div><div className="source-detail"><div className="source-icon"><Film size={22}/></div><div><strong>{source?.name??'Waiting for source'}</strong><p>{source?`${clock(source.duration)} · ${source.fps.toFixed(2)} fps · recorded source`:'Original recording'}</p></div></div><div className="provenance-rows"><div><span>Measurement method</span><strong>{analysisMethod}</strong></div><div><span>Analysis</span><strong className={analysis?'lime-text':''}>{analysis?'Saved analysis · replay':job.status==='running'?'Computing':'Not available'}</strong></div><div><span>Sample rate</span><strong>{analysis?`${analysis.sample_fps} fps`:'—'}</strong></div><div><span>VSS services</span><strong className={health.vss.available?'lime-text':'muted'}>{health.vss.available?'Connected':'Not connected'}</strong></div></div>{health.vss.available&&health.vss.base_url?<a className="text-button" href={health.vss.base_url} target="_blank" rel="noreferrer">Open VSS workspace <ExternalLink size={13}/></a>:<p className="source-explanation">Select a recording from VSS. Measurements are bound to its actual VIOS stream identity and source offsets.</p>}</section>
        </div>
        {isCycleAnalysis?<CycleResults cycles={cycles} selectedId={selectedCycle?.id??null} time={time} duration={source?.duration??0} select={selectCycle} evidence={openCycleEvidence}/>:<section className="panel timeline-panel" id="timeline"><div className="panel-topline"><div className="panel-title"><Film size={16}/><h2>The process, in context</h2></div><span className="reference-tag"><Eye size={13}/> Human-reviewed chapters</span></div><div className="timeline-wrap"><div className="chapter-track">{source?.chapters.map((chapter,index)=><button key={chapter.id} title={`${chapter.label}: ${chapter.description}`} className={`chapter-block ${currentChapter?.id===chapter.id?'active':''}`} onClick={()=>jumpChapter(chapter)} style={{flex:Math.max(6,chapter.end-chapter.start),'--chapter-color':['#b5eb47','#83bd82','#c9bb78','#93b2ba','#9e9bc5','#bd9d81'][index%6]} as React.CSSProperties}><span className="chapter-index">{(index+1).toString().padStart(2,'0')}</span><strong>{chapter.label}</strong><span>{clock(chapter.start)} — {clock(chapter.end)}</span></button>)}</div><div className="source-timeline"><span>00:00</span><div><i style={{left:`${time/(source?.duration||108)*100}%`}}/></div><span>{clock(source?.duration??0)}</span></div><div className="chapter-description"><span className="chapter-description-label">{currentChapter?.label??'Between chapters'}</span><p>{currentChapter?.description??'Select a chapter to review its source footage. Measurements are available only in calibrated views.'}</p>{currentChapter&&<button className="text-button" onClick={()=>openEvidence((currentChapter.start+currentChapter.end)/2,currentChapter.label)}>Evidence <ArrowUpRight size={13}/></button>}</div>{!!analysis?.events.length&&<div className="measured-events"><span className="eyebrow"><Activity size={12}/> MEASURED MOMENTS</span><div>{analysis.events.map(event=><button key={event.id} title={event.detail} onClick={()=>{seek(event.t);openEvidence(event.t,event.detail);}}><span>{clock(event.t,true)}</span>{event.label}<ArrowUpRight size={12}/></button>)}</div></div>}</div></section>}
        <section className="panel query-panel" id="query"><div className="query-intro"><div className="query-icon"><MessageSquare size={21}/></div><div><h2>Ask the measurements</h2><p>Answers from measured data, with source moments you can open.</p></div><span className="pill subtle">MEASUREMENT TOOLS</span></div><form className="query-form" onSubmit={event=>{event.preventDefault();void ask();}}><Search size={18}/><input aria-label="Ask a measurement question" placeholder={isCycleAnalysis?cycleQuestion:"Which bottle reached the reference level first?"} value={question} onChange={event=>setQuestion(event.target.value)} disabled={!analysis}/><button className="button primary" type="submit" disabled={queryLoading||!analysis||!question.trim()}>{queryLoading?<LoaderCircle className="spin" size={16}/>:<ArrowRight size={17}/>}<span>{queryLoading?'Looking up':'Ask'}</span></button></form><div className="query-examples">{(isCycleAnalysis?[cycleQuestion,'Which bottles overflowed? Show their evidence.','Summarize the completed bottle inspection.']:['Which bottle reached the reference level first?','Compare the bottles in this filling scene.','What measurements are available?']).map(text=><button key={text} onClick={()=>void ask(text)} disabled={!analysis||queryLoading}>{text}<ArrowUpRight size={12}/></button>)}</div>{queryError&&<p className="error-text" role="alert">{queryError}</p>}{queryResult&&<div className="query-answer" aria-live="polite"><div><span className={`status-dot ${queryResult.supported?'lime':'offline'}`}/><span>{queryResult.supported?'MEASUREMENT RESULT':'OUTSIDE AVAILABLE MEASUREMENTS'}</span></div><p>{queryResult.answer}</p><div className="query-evidence">{queryResult.evidence.map((item,index)=><button className="button secondary" key={`${item.t}-${index}`} onClick={()=>{seek(item.t);openEvidence(item.t,item.label);}}><Film size={13}/>{clock(item.t,true)} <span>{item.label}</span><ArrowUpRight size={12}/></button>)}</div><span className="small-note">Deterministic measurement tools · not an LLM response</span></div>}</section>
        <footer className="app-footer"><span><ScanLine size={13}/> VSS FILLING ANALYSIS</span><span>{source?`SOURCE ${source.sha256.slice(0,8)}`:'WAITING FOR SOURCE'}</span></footer>
      </main>
    {evidence&&source&&<EvidenceDrawer range={evidence} source={source} onClose={closeEvidence} seek={seek}/>}
    {showInfo&&createPortal(<div className="vss-filling vss-filling-portal"><div className="drawer-backdrop" onClick={()=>setShowInfo(false)}><section className="info-dialog" role="dialog" aria-modal="true" aria-labelledby="info-title" onClick={e=>e.stopPropagation()}><div className="drawer-header"><div><span className="eyebrow">PROVENANCE & LIMITS</span><h2 id="info-title">What the console measures</h2></div><button className="icon-button" aria-label="Close analysis details" onClick={()=>setShowInfo(false)}><X size={20}/></button></div><p>{neuralMeasurements?'Liquid height is derived from RF-DETR bottle and liquid masks. Underfill compares completed bottles with a reviewed camera reference. Overflow uses a separate exterior-color signal; it is not inferred by the fill-height model. These are visible-height estimates, not volume or factory quality certification.':isCycleAnalysis?'The completed-cycle inspection estimates visible liquid height within a camera-specific region and separately checks for exterior liquid. Its normal/underfill reference is a comparison for this recording, not an industrial quality specification. Results can be uncertain and should be checked against source evidence.':'Liquid height is estimated inside calibrated image regions. It is not a volume measurement, fill-quality certification, or automated spill verdict. Camera cuts reset bottle identities.'}</p><dl><dt>Source SHA-256</dt><dd className="hash">{source?.sha256??'Unavailable'}</dd><dt>Algorithm</dt><dd>{analysis?.algorithm??'Not analyzed'}</dd><dt>Analysis version</dt><dd>{analysis?.version??'—'}</dd><dt>Measured samples</dt><dd>{analysis?.samples.length??0}</dd><dt>Compute duration</dt><dd>{analysis?`${analysis.runtime_seconds.toFixed(2)} seconds`:'—'}</dd><dt>VSS connection</dt><dd>{health.vss.available?'Connected':health.vss.configured?'Configured, currently unavailable':'Not configured'}</dd></dl><div className="info-note"><Eye size={17}/><p>{isCycleAnalysis?'Bottle cycles, curves and inspection results are computed from the selected recording. Manual anomaly labels are not used as UI results. Reanalyze recomputes the analysis from the source.':'Process chapters are human-reviewed references. Numeric curves and overlays come from the analysis result. Reanalyze recomputes them from the source.'}</p></div><button className="button secondary" onClick={()=>{setShowInfo(false);void startAnalysis(true);}} disabled={job.status==='running'}><RefreshCw size={15}/>Recompute analysis</button></section></div></div>,document.body)}
  </div>;
}

export default function FillingAnalysis(props: Props) {
  const [mode, setMode] = useState<'recording' | 'live'>('recording');
  useEffect(() => { if (props.sourceRequest) setMode('recording'); }, [props.sourceRequest?.request_id]);
  return <div className="filling-mode-shell">
    <div className={`vss-filling filling-mode-bar ${props.theme === 'light' ? 'vss-filling-light' : ''}`}><div role="tablist" aria-label="Filling analysis mode">
      <button role="tab" aria-selected={mode === 'recording'} onClick={() => setMode('recording')}><Film size={14}/>Recording</button>
      <button role="tab" aria-selected={mode === 'live'} onClick={() => setMode('live')}><Activity size={14}/>Live</button>
    </div><span>{mode === 'live' ? 'Continuous stream · measurements as frames arrive' : 'Recorded source · inspect analyzed frames'}</span></div>
    <div className="filling-mode-content" hidden={mode !== 'recording'}><RecordingAnalysis {...props} isActive={(props.isActive ?? true) && mode === 'recording'}/></div>
    {mode === 'live' && <div className="filling-mode-content"><LiveFilling theme={props.theme} active={props.isActive ?? true} submitChatMessage={props.submitChatMessage} onChatContextChange={props.onLiveChatContextChange}/></div>}
  </div>;
}
