# SPDX-FileCopyrightText: Copyright (c) 2020-2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

FROM nvcr.io/nvidia/cuda:13.2.0-runtime-ubuntu24.04

# Install all the dependent packages
RUN apt-get update && \
	DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
        libcurl4 \
        libxml2 \
        libssl3t64 \
        libjsoncpp25 \
        libsqlite3-0 \
        libuuid1 \
        gstreamer1.0-plugins-base \
        gstreamer1.0-plugins-good \
        libgstreamer1.0-0 \
        libgstreamer-plugins-base1.0-0 \
        libboost-filesystem1.83.0 \
        libboost-thread1.83.0 \
        gstreamer1.0-tools \
        libjansson4 \
        librdkafka1 \
        libcairo2 \
        libpango-1.0-0 \
        libpangocairo-1.0-0 \
        libpqxx-7.8t64 \
        libhiredis1.1.0 \
	libpaho-mqttpp3-1 \
        && apt-get clean

# Kafka producer/consumer load the unversioned name with dlopen(). The runtime
# package only ships the SONAME; provide the linker-name symlink without
# installing librdkafka-dev in the release image.
RUN ln -s /usr/lib/x86_64-linux-gnu/librdkafka.so.1 /usr/lib/x86_64-linux-gnu/librdkafka.so

# To get video driver libraries at runtime (libnvidia-encode.so/libnvcuvid.so)
ENV NVIDIA_DRIVER_CAPABILITIES=$NVIDIA_DRIVER_CAPABILITIES,video,compute,graphics,utility
RUN ln -s /usr/lib/x86_64-linux-gnu/libnvcuvid.so.1 /usr/lib/x86_64-linux-gnu/libnvcuvid.so
RUN ln -s /usr/lib/x86_64-linux-gnu/libnvidia-encode.so.1 /usr/lib/x86_64-linux-gnu/libnvidia-encode.so

# OSRB requirement, GPL licensed packages removal
RUN rm -f /usr/lib/x86_64-linux-gnu/gstreamer-1.0/libgstaudioparsers.so* \
        /usr/lib/x86_64-linux-gnu/gstreamer-1.0/libgstx264.so* \
        /usr/lib/x86_64-linux-gnu/gstreamer-1.0/libgstfaad.so* \
        /usr/lib/x86_64-linux-gnu/gstreamer-1.0/libgstvoaacenc.so*

RUN rm -f /usr/lib/x86_64-linux-gnu/libavresample* /usr/lib/x86_64-linux-gnu/libavutil* \
        /usr/lib/x86_64-linux-gnu/libavcodec* /usr/lib/x86_64-linux-gnu/libavformat* \
        /usr/lib/x86_64-linux-gnu/libavfilter*  /usr/lib/x86_64-linux-gnu/gstreamer-1.0/libgstde265.so* \
        /usr/lib/x86_64-linux-gnu/gstreamer-1.0/libgstx265.so* /usr/lib/x86_64-linux-gnu/libde265.so* /usr/lib/x86_64-linux-gnu/gstreamer-1.0/libgstvpx.so*

RUN rm -f /usr/lib/x86_64-linux-gnu/libmpeg2.so* /usr/lib/x86_64-linux-gnu/libmpeg2encpp-2.1.so* /usr/lib/x86_64-linux-gnu/libmpg123.so*  \
        /usr/lib/x86_64-linux-gnu/libx265.so* /usr/lib/x86_64-linux-gnu/libx264.so* /usr/lib/x86_64-linux-gnu/libvpx.so*  \
        /usr/lib/x86_64-linux-gnu/libmpeg2convert.so* /usr/lib/x86_64-linux-gnu/gstreamer-1.0/libgstopenh264.so* \
        /usr/lib/x86_64-linux-gnu/gstreamer-1.0/libgstnvcodec.so*

RUN rm -f /usr/lib/x86_64-linux-gnu/gstreamer-1.0/libgstuvch264.so* /usr/lib/x86_64-linux-gnu/libopenh264.so* \
        /usr/lib/x86_64-linux-gnu/libvo-aacenc.so* /usr/lib/x86_64-linux-gnu/libmp3lame.so* \
        /usr/lib/x86_64-linux-gnu/libfaad* /usr/lib/x86_64-linux-gnu/libFLAC.so* \
        /usr/lib/x86_64-linux-gnu/libmjpegutils-2.1.so.0* /usr/lib/x86_64-linux-gnu/libxvidcore.so* /usr/lib/x86_64-linux-gnu/gstreamer-1.0/libgstmpegpsmux.so* \
        /usr/lib/x86_64-linux-gnu/gstreamer-1.0/libgstflac.so* \
        /usr/lib/x86_64-linux-gnu/gstreamer-1.0/libgstmpeg2enc.so* \
        /usr/lib/x86_64-linux-gnu/gstreamer-1.0/libgstmpeg2dec.so*

# Intel MediaSDK / QuickSync (libmfx) HW codec stack -- unused (VST uses NVENC/NVDEC).
# Carries H.264/H.265 codec royalty exposure. Remove dispatcher, HW runtime, tracer,
# all AVC/HEVC/etc HW plugins, and the GStreamer msdk/qsv plugins.
RUN rm -f /usr/lib/x86_64-linux-gnu/mfx/libmfx_*_hw64.so* \
        /usr/lib/x86_64-linux-gnu/libmfx.so* /usr/lib/x86_64-linux-gnu/libmfxhw64.so* \
        /usr/lib/x86_64-linux-gnu/libmfx-tracer.so* \
        /usr/lib/x86_64-linux-gnu/gstreamer-1.0/libgstmsdk.so* \
        /usr/lib/x86_64-linux-gnu/gstreamer-1.0/libgstqsv.so* && \
    rm -rf /usr/lib/x86_64-linux-gnu/mfx

# FFmpeg scaling/resampling/postproc leftovers -- orphaned (libav* removed above, nothing
# links these). Flagged by OSRB; remove to eliminate remaining FFmpeg royalty/GPL exposure.
RUN rm -f /usr/lib/x86_64-linux-gnu/libswscale.* \
        /usr/lib/x86_64-linux-gnu/libswresample.* \
        /usr/lib/x86_64-linux-gnu/libpostproc.*

# Prune codec libraries and GStreamer codec plugins not selected by VIOS.  Keep
# the JPEG/PNG and XML dependencies required by the packaged application.
RUN rm -f /usr/lib/x86_64-linux-gnu/libaom.so* \
        /usr/lib/x86_64-linux-gnu/libldacBT_enc.so* \
        /usr/lib/x86_64-linux-gnu/liblc3.so* \
        /usr/lib/x86_64-linux-gnu/libdv.so* \
        /usr/lib/x86_64-linux-gnu/libflite.so* \
        /usr/lib/x86_64-linux-gnu/libfluidsynth.so* \
        /usr/lib/x86_64-linux-gnu/libfreeaptx.so* \
        /usr/lib/x86_64-linux-gnu/libgme.so* \
        /usr/lib/x86_64-linux-gnu/libgsm.so* \
        /usr/lib/x86_64-linux-gnu/libgssdp-1.6.so* \
        /usr/lib/x86_64-linux-gnu/libinstpatch-1.0.so* \
        /usr/lib/x86_64-linux-gnu/libjbig.so* \
        /usr/lib/x86_64-linux-gnu/liblcms2.so* \
        /usr/lib/x86_64-linux-gnu/libogg.so* \
        /usr/lib/x86_64-linux-gnu/libOpenEXR*.so* \
        /usr/lib/x86_64-linux-gnu/libopenmpt.so* \
        /usr/lib/x86_64-linux-gnu/libmodplug.so* \
        /usr/lib/x86_64-linux-gnu/libmpcdec.so* \
        /usr/lib/x86_64-linux-gnu/libWildMidi.so* \
        /usr/lib/x86_64-linux-gnu/libopenjp2.so* \
        /usr/lib/x86_64-linux-gnu/libopus.so* \
        /usr/lib/x86_64-linux-gnu/libspandsp.so* \
        /usr/lib/x86_64-linux-gnu/libspeex.so* \
        /usr/lib/x86_64-linux-gnu/libSvtAv1Enc.so* \
        /usr/lib/x86_64-linux-gnu/libtheora*.so* \
        /usr/lib/x86_64-linux-gnu/libtiff.so* \
        /usr/lib/x86_64-linux-gnu/libtwolame.so* \
        /usr/lib/x86_64-linux-gnu/libvo-amrwbenc.so* \
        /usr/lib/x86_64-linux-gnu/libvorbis*.so* \
        /usr/lib/x86_64-linux-gnu/libwavpack.so* \
        /usr/lib/x86_64-linux-gnu/libwebp.so* \
        /usr/lib/x86_64-linux-gnu/libwebpmux.so* \
        /usr/lib/x86_64-linux-gnu/libsharpyuv.so* \
        /usr/lib/x86_64-linux-gnu/libavc1394.so* \
        /usr/lib/x86_64-linux-gnu/librom1394.so* \
        /usr/lib/x86_64-linux-gnu/libiec61883.so* \
        /usr/lib/x86_64-linux-gnu/libdc1394.so* \
        /usr/lib/x86_64-linux-gnu/libcdda_interface.so* \
        /usr/lib/x86_64-linux-gnu/libcdda_paranoia.so* \
        /usr/lib/x86_64-linux-gnu/libchromaprint.so* \
        /usr/lib/x86_64-linux-gnu/libv4lconvert.so* \
        /usr/lib/x86_64-linux-gnu/gstreamer-1.0/libgstaom.so* \
        /usr/lib/x86_64-linux-gnu/gstreamer-1.0/libgst1394.so* \
        /usr/lib/x86_64-linux-gnu/gstreamer-1.0/libgstcdparanoia.so* \
        /usr/lib/x86_64-linux-gnu/gstreamer-1.0/libgstchromaprint.so* \
        /usr/lib/x86_64-linux-gnu/gstreamer-1.0/libgstcolormanagement.so* \
        /usr/lib/x86_64-linux-gnu/gstreamer-1.0/libgstdv.so* \
        /usr/lib/x86_64-linux-gnu/gstreamer-1.0/libgstdc1394.so* \
        /usr/lib/x86_64-linux-gnu/gstreamer-1.0/libgstflite.so* \
        /usr/lib/x86_64-linux-gnu/gstreamer-1.0/libgstfluidsynthmidi.so* \
        /usr/lib/x86_64-linux-gnu/gstreamer-1.0/libgstgme.so* \
        /usr/lib/x86_64-linux-gnu/gstreamer-1.0/libgstgsm.so* \
        /usr/lib/x86_64-linux-gnu/gstreamer-1.0/libgstlc3.so* \
        /usr/lib/x86_64-linux-gnu/gstreamer-1.0/libgstldac.so* \
        /usr/lib/x86_64-linux-gnu/gstreamer-1.0/libgstmidi.so* \
        /usr/lib/x86_64-linux-gnu/gstreamer-1.0/libgstmodplug.so* \
        /usr/lib/x86_64-linux-gnu/gstreamer-1.0/libgstogg.so* \
        /usr/lib/x86_64-linux-gnu/gstreamer-1.0/libgstopenaptx.so* \
        /usr/lib/x86_64-linux-gnu/gstreamer-1.0/libgstopenexr.so* \
        /usr/lib/x86_64-linux-gnu/gstreamer-1.0/libgstopenjpeg.so* \
        /usr/lib/x86_64-linux-gnu/gstreamer-1.0/libgstopenmpt.so* \
        /usr/lib/x86_64-linux-gnu/gstreamer-1.0/libgstopus.so* \
        /usr/lib/x86_64-linux-gnu/gstreamer-1.0/libgstopusparse.so* \
        /usr/lib/x86_64-linux-gnu/gstreamer-1.0/libgstspandsp.so* \
        /usr/lib/x86_64-linux-gnu/gstreamer-1.0/libgstspeex.so* \
        /usr/lib/x86_64-linux-gnu/gstreamer-1.0/libgstsvtav1.so* \
        /usr/lib/x86_64-linux-gnu/gstreamer-1.0/libgsttheora.so* \
        /usr/lib/x86_64-linux-gnu/gstreamer-1.0/libgstteletext.so* \
        /usr/lib/x86_64-linux-gnu/gstreamer-1.0/libgsttwolame.so* \
        /usr/lib/x86_64-linux-gnu/gstreamer-1.0/libgstvoamrwbenc.so* \
        /usr/lib/x86_64-linux-gnu/gstreamer-1.0/libgstvorbis.so* \
        /usr/lib/x86_64-linux-gnu/gstreamer-1.0/libgstwavpack.so* \
        /usr/lib/x86_64-linux-gnu/gstreamer-1.0/libgstwebp.so* \
        /usr/lib/x86_64-linux-gnu/gstreamer-1.0/libgstwildmidi.so* \
        /usr/share/sounds/sf2/TimGM6mb.sf2

RUN rm -f /usr/lib/x86_64-linux-gnu/liba52* /usr/lib/x86_64-linux-gnu/libcdio.so* /usr/lib/x86_64-linux-gnu/libsidplay.so* \
        /usr/lib/x86_64-linux-gnu/liblrdf.so*  /usr/lib/x86_64-linux-gnu/libneon.so* \
        /usr/lib/x86_64-linux-gnu/libbs2b.so* /usr/lib/x86_64-linux-gnu/libdca.so* /usr/lib/x86_64-linux-gnu/libdvdnav.so* \
        /usr/lib/x86_64-linux-gnu/libdvdread.so* /usr/lib/x86_64-linux-gnu/libmplex2-2.1.so* /usr/lib/x86_64-linux-gnu/libsbc.so* \
        /usr/lib/x86_64-linux-gnu/libzvbi* && \
    rm -rf /usr/share/doc/libreadline8 /usr/lib/x86_64-linux-gnu/libreadline*

# Microservice compliance requirements
LABEL com.nvidia.mm.nspect="NSPECT-1H82-JYCQ"
