# From the root directory of your Logstash codebase ($LS_HOME), you can compile it with:
#   ./gradlew assemble (or gradlew.bat assemble if you're running on Windows)
# This should produce the $LS_HOME/logstash-core/build/libs/logstash-core-x.y.z.jar
# where x, y, and z refer to the version of Logstash.
#
# After you have successfully compiled Logstash, you need to tell your Java plugin
# where to find the logstash-core-x.y.z.jar file by setting the path below:
LOGSTASH_CORE_PATH=<target_folder>/logstash-core
