# SPDX-FileCopyrightText: Copyright (c) 2025-2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

upstream calibration-toolkit {
    server localhost:8004;
}
error_log /var/log/nginx/error.log debug;

server {
    rewrite_log on;
    client_max_body_size 1000M;
    error_log /var/log/nginx/localhost.error_log debug;
    listen 8003;
    server_name localhost;
    root /calibration/server/data;
    access_log /var/log/nginx/access.log;

    location ~* ^/([^/]+)/media/([^/]+\.(ttf|ttf.gz|woff2|woff|eot|eot.gz|svg|svg.gz))$ {
        # add_header content-type text/plain;
        # return 200 'location svg /$2 $http_host $server_name $host $remote_addr' ;
        root /usr/local/lib/python3.13/dist-packages/calibration/server/staticfiles/media/;
        autoindex on;
        client_max_body_size 1000M;
        try_files /$2 =404;

    }

    location ~ ^/([^/]+)/static/(.*)$ {
        # add_header content-type text/plain;
        # return 200 'location static $http_host';
        alias /usr/local/lib/python3.13/dist-packages/calibration/server/staticfiles/$2;
        autoindex on;
        client_max_body_size 1000M;
        # add_header content-type text/plain;
        # return 200 'location static';
    }

    location ~ ^/([^/]+)/media/(.*)$ {
        # add_header content-type text/plain;
        # return 200 'location media $uri $http_host';
        alias /calibration/server/data/media/$2;
        autoindex on;
        client_max_body_size 1000M;

    }

    location ~ ^/media/(.*)$ {
        # add_header content-type text/plain;
        # return 200 'location media for docker $uri $1 $http_host';
        alias /calibration/server/data/media/$1;
        autoindex on;
        client_max_body_size 1000M;

    }



    location ~ ^/([^/]+)/calibration(/.*)$ {
        add_header content-type text/plain;
        return 200 'location calibration';
        set $tenant_id $1;
        set $url_without_tenant $2;

        # Proxy requests to the Django application
        proxy_pass http://calibration-toolkit/$tenant_id/calibration/$url_without_tenant/;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $http_host;
        proxy_redirect off;

    }

    location ^~ /api/ {
        rewrite ^/api(/.*)$ /api$1 break;
        proxy_pass http://calibration-toolkit;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $http_host;
        proxy_redirect off;
    }

    location / {
        # Proxy requests to the Django application without a tenant ID
        proxy_pass http://calibration-toolkit/;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $http_host;
        proxy_redirect off;
        proxy_connect_timeout 500s;
        proxy_send_timeout 500s;
        proxy_read_timeout 500s;
        send_timeout 500s;
    }

    error_page 500 502 503 504 /50x.html;
    location = /50x.html {
        root /usr/share/nginx/html;
    }
}