# SPDX-FileCopyrightText: Copyright (c) 2025-2026, NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "search-analytics.fullname" . }}-search-analytics-config
  labels:
    {{- include "search-analytics.labels" . | nindent 4 }}
data:
  {{- if .Values.config.kafkaConfigJson }}
  vss-search-analytics-config.json: |
{{ .Values.config.kafkaConfigJson | indent 4 }}
  {{- else }}
  vss-search-analytics-config.json: |
    {
      "kafka": {
        "brokers": "{{ include "search-analytics.kafkaBootstrap" . }}",
        "group": "mdx-fusion-search-analytics-app",
        "consumer": {
          "autoOffsetReset": "latest",
          "enableAutoCommit": false,
          "maxPollIntervalMs": 900000,
          "maxPartitionFetchBytes": 10485760,
          "fetchMaxBytes": 104857600,
          "maxPollRecords": 10000,
          "timeout": 0.01
        },
        "producer": {
          "lingerMs": 0
        },
        "topics": [
          {"name": "raw", "value": "mdx-raw"},
          {"name": "behavior", "value": "mdx-behavior"},
          {"name": "embed", "value": "mdx-embed"},
          {"name": "embedFiltered", "value": "mdx-embed-filtered"},
          {"name": "notification", "value": "mdx-notification"}
        ]
      },
      "sensors": [],
      "app": [
        {"name": "behaviorWatermarkSec", "value": "30"},
        {"name": "behaviorStateTimeout", "value": "10"},
        {"name": "behaviorMaxPoints", "value": "100"},
        {"name": "objectConfidenceThreshold", "value": "0.5"},
        {"name": "coordinateSystem", "value": "euclidean"},
        {"name": "embedEnableDownsampling", "value": "false"},
        {"name": "embedDownsamplerType", "value": "window"},
        {"name": "embedSensorTTLSec", "value": "3600"},
        {"name": "embedDownsampleToleranceMode", "value": "cosine"},
        {"name": "embedDownsampleSimilarityThreshold", "value": "0.90"},
        {"name": "embedDownsampleMaxIntervalSec", "value": "300"},
        {"name": "embedDownsampleWindowSize", "value": "60"},
        {"name": "embedDownsampleMinNeighbours", "value": "3"},
        {"name": "sourceType", "value": "kafka"},
        {"name": "sinkType", "value": "kafka"},
        {"name": "numWorkersForBehaviorCreation", "value": "2"},
        {"name": "numWorkersForEmbedFiltering", "value": "1"},
        {"name": "inSimulationMode", "value": "true"},
        {"name": "stateManagementFilter", "value": "[\"Person\"]"}
      ]
    }
  {{- end }}
