# SPDX-FileCopyrightText: Copyright (c) 2025-2026, NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: v1
kind: Service
metadata:
  name: {{ include "search-analytics.fullname" . }}-search-analytics
  labels:
    {{- include "search-analytics.labels" . | nindent 4 }}
    app.kubernetes.io/component: search-analytics
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.port }}
      targetPort: {{ .Values.port }}
      protocol: TCP
  selector:
    {{- include "search-analytics.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: search-analytics
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "search-analytics.fullname" . }}-search-analytics
  labels:
    {{- include "search-analytics.labels" . | nindent 4 }}
    app.kubernetes.io/component: search-analytics
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      {{- include "search-analytics.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: search-analytics
  template:
    metadata:
      labels:
        {{- include "search-analytics.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: search-analytics
    spec:
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: search-analytics
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - python3
            - apps/fusion_search/main_fusion_search_analytics_app.py
            - --config
            - /resources/vss-search-analytics-config.json
          ports:
            - name: http
              containerPort: {{ .Values.port }}
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: search-analytics-config
              mountPath: /resources/vss-search-analytics-config.json
              subPath: vss-search-analytics-config.json
              readOnly: true
      volumes:
        - name: search-analytics-config
          configMap:
            name: {{ include "search-analytics.fullname" . }}-search-analytics-config
